---
title: "1 Corinthians 11:2-16"
date: "2018-01-02"
categories: []
tags: []
typora-root-url: ../../public/
bibliography: Library.bib
draft: true
---

Paul gives guidance on conduct of women when praying and prophesying in church. This post attempts to deal with the percieved contradiction between this passage and 1 Cor 14.

>But I want you to know that Christ is the head of every man(Gk. aner), and the man(Gk. aner) is the head of a woman(Gk. gyne), and God is the head of Christ.
>— 1 Corinthians 11:3

Is the correct translation in v3 “man” or “husband”?

The Greek words for man and woman in the NET have some ambiguity. Most translations (NIV, KJV, NASB) render these words the same as the NET with man and woman. However, a few translations differ.

- AMP: the head of a *woman* is her *husband*
- YLT: the head of a *woman* is the *husband*
- ESV: the head of a *wife* is her *husband*

^ the ESV goes one step further by rendering the word for woman as “wife” is to match the context of “husband”

> ”Paul wants the Corinthians to understand that Christ is the head of every man (more likely ‘husband’), and the ‘husband’ is head of every woman (more likely ‘wife’, given the ambiguity of these words in Greek).”
> —  The New Bible Commentary

^ This view is further confirmed in the *New Bible Commentary* notes on 1 Cor 11.

^ So why the ambiguity? I believe this is answered by first looking at what Paul means when he talks about “headship”.

## What does Paul mean by “headship”?

^ Paul is talking to a church mainly populated by Jewish people so it would be first of all be useful to explore what the Jewish understood about the term “headship”.

> Rebekah looked up and saw Isaac. She got down from her camel and asked Abraham’s servant, “Who is that man walking in the field toward us?” “That is my master,” the servant replied. So she took her veil and covered herself.
> — Genesis 24:64–65

^ Through this act, Rebekah demonstrated that she was ready and willing to accept the the headship of Isaac through the bond of marriage. Dating back to Genesis, head coverings were a cultural sign of submission to a husband.

^ consider the Jewish teaching on vows in Numbers 30

> But if her husband remains completely silent about her from day to day, he thus confirms all her vows or all her obligations which she is under; he confirms them because he remained silent about when he heard them. But if he should nullify them after he has heard them, then he will bear her iniquity.”
> — Numbers 30:14–15

^ A husband can bear the inequity of his wife if he chooses

> But every vow of a widow or of a divorced woman which she has pledged for herself will remain intact.
> — Numbers 30:9

^ However, if there is no husband, then a vow will remain intact

- - - -

^ **Devotional Note:**

> Husbands, love your wives just as Christ loved the church and gave himself for her
> — Ephesians 5:25

^ choose to bear the inequity of your wives

> So then, just as sin entered the world through one man and death through sin, and so death spread to all people because all sinned—for before the law was given, sin was in the world, but there is no accounting for sin when there is no law. Yet death reigned from Adam until Moses even over those who did not sin in the same way that Adam (who is a type of the coming one) transgressed.
> — Romans 5:12–14

^ Adam was named the culprit even though it was Eve’s transgression

- - - -

> because the husband(aner) is the head of the wife(gyne) as also Christ is the head of the church—he himself being the savior of the body.
> — Ephesians 5:23

^ Christ is the saviour of the body by bearing our iniquity on the cross

> Let us rejoice and exult and give him glory, because the wedding celebration of the Lamb has come, and his bride has made herself ready.
> — Revelation 19:7

^ this idea is further continued in Rev 19 when the marriage of Christ and his bride, the church, has come.

- - - -

^ **Devotional Note:**

^ This idea reminds me that we as a church have a bonding marriage engagement with Christ the will not be broken.

Gen 24.64-65
Mat16.18
Mat1.20
1Ti2:14
Romans 5:12–14

brings up in my mind the way Jewish marriages were seen in those times. Mary and Joseph were engaged to be married. But due to suspicion of unfaithfulness, Joseph was considering a divorce. The word divorce made me realise how bonding an engagement was in those times. John in Revelation 19 was letting those he was writing to know that those who are in Christ are in a bonding engagement with Him.

- - - -

^ Summary: Being the “head” of someone is a different idea to “exercising authority” over someone. In old money, if you are were head of someone, then you would you have the ability to bear their iniquity.

> because the husband(aner) is the head of the wife(gyne) as also Christ is the head of the church—he himself being the saviour of the body.
> — Ephesians 5:23

^ Going back to Eph 5, Paul tackles the same topic as 1 Cor 11 using the same Greek words and leaving us in no doubt that a husband is head of his wife

^ However, this brings us to the Question:

## Are all brothers in Christ the head of all sisters in Christ?

^ “But wait, hold on…1 Corinthians 11 is in the context of the church while Ephesian 5 is in the Context of a marriage. Doesn’t 1 Cor11 extend this headship to all men in the church, not just the husband?”

^ Short answer: No.

- - - -

- - - -

**…WORK IN PROGRESS…**

> because the husband(aner) is the head of the wife(gyne) as also **Christ is the head of the church—he himself being the savior of the body.**
> — Ephesians 5:23

^ Going back to Ephesians 5, Paul brings up a clear link to headship between the whole church and the intercession that took place on the cross

> Let us rejoice and exult and give him glory, because the wedding celebration of the Lamb has come, and his bride has made herself ready.
> — Revelation 19:7

Because of this, the context must be considered. The ESV chose to render *gyne* as “wife” in both instances (both Ephesians and 1Corinthinians). I asked an elder about this ambiguity “who is the head of a widow in both church and at home?” The answer I got was that when they are at home, Christ is their head and when they are gathered together as a church all men are their head.

Revelations gives the clear picture that Jesus bears the church’s iniquities through marriage of the church as a whole.




> But I do not allow a woman to teach or exercise authority over a man. She must remain quiet.
> — 1 Timothy 2:12



This is indicated in Num 30 where if a woman is under the care of her father or husband, the father/husband can “overrule” or “bear the iniquity”. However, if you are a widow or divorced, you must fulfil that vow. This suggests to me that if you are unmarried and not living in your father’s house then Christ is your head and not “all men”.

**Parallel Verses**



> When you make a vow to the LORD your God you must not delay in fulfilling it, for otherwise he will surely hold you accountable as a sinner.
> — Deuteronomy 23:21





^ The focus of this passage is to eradicate the practice of male headcoverings and not the common understanding of implementing a practice of email headcoverings. I’ve detailed below the reasons why I came to this conclusion.

^ For this reason I struggle to see any evidence that male church members who are not joined in marriage have headship over a woman they are not married to.

## Verse 16

> “The custom is the acceptance of an equality of status in accordance with which woman may lead in public prayer or preaching (see below on prophecy) side by side with a recognition that gender differences must not be blurred but appreciated, valued, and expressed in appropriate ways in response to God’s unrevoked decree.”
> — Excerpt From: Anthony C. Thiselton. “NIGTC_The First Epistle to the Corinthians (NIGTC).” iBooks.

^ This Commentator believes that a woman was to wear a head coverings, but were also to ensure that gender roles were not blurred

> “Chrysostom and Calvin surprisingly argue that the universal church practice to which Paul appeals is a lack of “delight in stirring up quarrels” without “attention to truth.”
> — Excerpt From: Anthony C. Thiselton. “NIGTC_The First Epistle to the Corinthians (NIGTC).” iBooks.

^ Chrysostom and Calvin believe the quarrelling should be eradicated “we have no such practice in quarrelling”
