---
title: "Apostate Christendom"
slug: "apostacy1"
date: "2018-01-01"
categories: []
tags: [cog]
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---

> “Two ministers were talking one to another one time and one was trying to be charitable and said, ‘You know, we both serve God. You in your way and I in His.’” — Douglas Wilson 

What i've learned over the last few years is this - name calling doesn't win anyone. I got banned recently for calling a group "elitists"  for holding views I didnt hold. Don't get me wrong, I was right, but there was no profit in name calling. 

The term Apostate is used x time in scripture.In the needed truth, it's used x times

The use of the term apostate (or apostasy) is used once in the scripture.

I was joking with my father one time and said, the only reason I would leave the Churches of God would be if I came to the conclusion that it was apostate. Some time later, we were sitting having lunch and I declared that "I had decided the Churches of God wasn't apostate". Of course it was a ridiculous statement. 
He told me he could believe how arrogant I was for even considering aligning the term apostate with his church. to  (he didn't get the joke). He also got quite upset when I referred to it as the title "Needed Truth Brethren". His reason for getting upset, was that it was the designation often used by Open-Brethren. It was also suggesting that they were just another denomination and not the 'one true church' as many of they claim to be. 

I had just been engrossed a lot of the early Needed Truth articles where the term is so frequently used. Out of intertest, I carried an exercise one afternoon and calculated every time a needed truth article used the words "apostate" or "apostasy" (Yes I know I'm a geek).

I then compared this finding to the frequency it's used in scripture.

Here were my results.



Of course this doesn't really tell us much unless we look into detail 
to some of the uses in the articles...


Conclusion

Apostasy! Is the battle cry of divisive sects. If we consider other more apostate than ourselves, then we will continue in our apostasy. We think we have it! New light revealed.

The common use of the term "apostasy" or "apostate" is a un-profitable. Suppose if some one was to look at the Churches of God group and declare that since they had seemed to implant a governance out with the local church, another group would shout "you are falling down the slippery slope of apostasy!". All that would achieve would be getting peoples backs up and it would be no help in the . Ofc course they would be proud of their argument that this is not a "teir" system, but infact a "sphere" system. But in the implenetation of this sphere system, there is a history of higher spheres having the authority to over rule the smaller spheres. The belief was that the smaller spheres were considered incompetent to make local decisions in some matters. Decisions could be over ruled by the wider spheres. Take for example the Vernal splinter group of 1907. A decision was made in the local/district sphere to discipline an elder. This was over ruled by the wider sphere and the elder was reestablished into his former position. A similar instance happened in Ayr were a man named Vernal, who led a splinter group by that name into an independently governed group of churches who maintained the principles.

This group not long after later had written to the churches of God requesting to be considered as part of the wider Fellowship, but insisted that they reject any authority out with the local level. The differences between these 2 groups were negligible.

 There may even be some reading that statement who have already got their back up on this point...