---
title: Article Review - Bad Faith
date: "2018-01-01"
categories: []
tags: [cog]
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---

https://granta.com/bad-faith/

Bad Faith - Ken Follett (ex-CoG movement turned athiest)


> *Every sect needs jargon. We did not have churches, we had halls; services were called meetings; the congregation was the assembly; the elders were overseers.*


> *The Fellowship paid much more attention to the petty rules of Paul than to the open-hearted wisdom of Jesus.*


> *At the age of fifteen, Dad went to a meeting of the Open Brethren. Now, the distance between their [the open-brethren] beliefs and ours [the CoG movement] was the breadth of a hair.*

Practically, the difference between the practices of the Gospel Hall movement churches and the CoG movement churches are the breadth of a hair. They have a larger number of assemblies who have maintained the traditions compared to the CoG movement. There are other churches who have went on to do their own thing and dissassociate them selves with the traditional practices/understandings of the brethren movememt. In the UK, many of them have linked with other moevemnts who are similarly attempting to move away from their traditional understandings. For example, the FIEC is a UK wide orginisation which encompass churches from independent churches who historically were from the baptist/free churches/open-brethren persuasion. they are known under the umbrella of the FIEC. Locally, we have a group called the West of Scotland Gospel Partnership. To believe that these churches would not have a visions for unity within the local church would be quite an ignorant perspective.

> *It was an egregious sin to enter a church of another denomination – especially another branch of the Brethren...A brother from another town could take part in our meetings only if he brought with him a letter of commendation from the overseers of his assembly. The Open Brethren, by contrast, would welcome anyone who said he belonged without checking, hence their name. I know of no other difference. And yet my father got into serious trouble...He was seen coming out of that den of heresy*

Christians *should not criticize other people’s forms of worship.*

> *I bought a guitar, and did not use it to play hymns.*

Now allowed to buy musical instruments - The inconsistency is similar to that of being able to buy a guitar, but not being able to use it to worship

> *I felt I had been duped...Most of all I was angry that I had believed the rubbish I had been fed. Nothing is more infuriating than the revelation that one has been stupid.*

Through this I became angry. I felt that the movement had stinted my growth as a Christian with their emphasis on misunderstandings of scripture. I started feeling like a failure for being duped. When I read my bible now and read other perspectives, my theology now from what it looked like 6 months ago is almost non recognizable. The understanding of 		


> *I began to visit cathedrals and  read about them  And I was soon struck by the questions that occur to most people when looking at such a building: Why is this here? Why did the people of the Middle Ages want one of these? And they wanted them badly. A cathedral cost a fortune – a moon shot is a comparable modern project – yet the men and women who put it up lived in wooden houses without chimneys and slept on the floor. Construction was  extraordinarily difficult with hammer and chisel and an iron measuring  rod.*


He was attracted back to Christianity by the thought of the passion of Christians who wanted to gorify God through art work and monestaries. I don't personally agree with this form of worship and wouldn't condone it myself, but who am I to criticise another persons form of worship.

*Context*

Writer grew up in Cardiff Wales, born into in the CoG Movement in the 1950s when the movement wer very strict it terms of watching TV, reading books. Studies Philospohy in university where he chose to reject the biblical philosphies in light of alternatives

*Initial Opinions/Views*



*What the Experts Say*



*Reflections*

If there was a local church in which I shared their values, I would meet with them. Unfortunately, there isn't. I agree with all their core values on unity, discipline etc. but of course don't fully share all there views in which the Green-view leadership have decided on. I know that even with in the leadership team there are clear differences in opinions on doctrinal/postional teachings, but they work hard to be an example to their church that, despite their differences, they agree together in one mind for the sake of the local unity.The governance allows for individual convictions withut insisting on their own way. 

They do not see all the epistle's teaching as prescriptive, instead they are useful.
<!--stackedit_data:
eyJoaXN0b3J5IjpbMTcwMjkwMTU4M119
-->