---
title: "Book Review: Against the Flow"
date: "2018-01-01"
categories: [review]
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---

- If God is real, how could a pagan emperor like Nebuchadnezzar violate the sanctity of God’s unique temple and get away with it? Why did God do nothing? This is in essence the hard question that is still very much with us today in a thousand different specific forms.
- The temple in Jerusalem was nothing but a building, its vessels nothing but human artefacts, however beautiful and valuable. The idea that God, if there were a God, would be interested in such an insignificant matter is patently absurd.
    * We are his temple - we are seemingly insignificant.
- Does God stop them with a bolt of lightning from the sky?
    * Why doesn't God do this today? Breaking of bread, withholding money from church?
- God was behind Nebuchadnezzar’s victory: And the Lord gave Jehoiakim king of Judah into his hand… (Daniel 1:2).
- Next time that somebody tells you that something is true, why not say to them: “What kind of evidence is there for that?” And if they can’t give you a good answer, I hope you’ll think very carefully before you believe a word they say. (Dawkins, 2003, page 248.)
- I think that a case can be made that faith is one of the world’s great evils, comparable to the smallpox virus but harder to eradicate. Faith, being belief that isn’t based on evidence, is the principal vice of any religion.3
- its independence from evidence is its joy, shouted from the rooftops”.
- However, taking Dawkins’ own advice, headlined above, we must ask: what is the evidence that religious faith is not based on evidence?
- The apostle Paul says what many pioneers of modern science believed, that nature itself is part of the evidence for the existence of God: For his invisible attributes, namely, his eternal power and divine nature, have been clearly perceived, ever since the creation of the world, in the things that have been made. So they are without excuse. (Romans 1:20.)
    * The built environment and the commercial interest of humans have conceild this beauty.
- In an exhibition of breathtaking inconsistency, evidence is the very thing he fails to supply for his claim that faith rejoices in the independence of evidence. And the reason he fails to supply such evidence is not hard to find, for there is none.
    * Proverbs 18:13 (ESV)13 If one gives an answer before he hears, it is his folly and shame
- In our world today inconsistent moral behaviour on the part of those who claim to follow Christ devalues the Christian faith and causes people to mock it.
    * Similar to NBP quote
- would you be happy if I now dismiss you and all your knowledge of physics because you cannot explain to me the nature of energy? After all, energy is surely by definition much less complex than the God who created it?”

    * Trinity
- we need to grasp that it is not only believers in God who believe in concepts they do not fully understand. Scientists do as well.
- what we think is harm looks different from God’s eternal perspective?
- Babylon was a spectacular city, in a completely different category from anything a young man from Judah could ever have seen or even imagined. It was in fact the largest city in the world at the time, covering over 1,000 hectares (2,500 acres).
    * Babylon and Rome?
- (According to Herodotus the walls were 80 feet thick, 320 feet high and 56 miles long, though this is disputed by archaeologists, who reckon that the walls were only 11 miles long and not nearly as high.)
- atheism-inspired communism has been responsible for more bloodshed than all religiously motivated conflicts put together,
- We need, however, to take their criticisms seriously, since Christendom has been tragically scarred by sad and inexcusable scandals,
- Peter, had taken a wild sweep with a sword and cut off the ear of the high priest’s servant, Jesus had told Peter to put his sword away, and healed the ear.
- The main implication of all this is obvious. Anyone who uses force of any kind to impose Christ’s message on people is acting in defiance of Christ’s explicit commands.
- The existence of counterfeit money does not prove that the real and genuine thing does not exist,

**4. A Question of Identity** 

- Nebuchadnezzar, although undoubtedly a ruthless absolute monarch, was sufficiently intelligent and far-sighted not to adopt a policy of total oppression in governing the disparate peoples of his empire. He believed that he could change people, and hence he deliberately chose the most able of the captives from any nation he conquered, and trained them thoroughly. They had to be young – older people are often fixed in their ways and cannot be moulded
    * God gave Daniel and friends a way in to the court of the king. If this was simply a small village tribe leader, there wouldn't be much written about it.
- He insisted on a three-year intensive cultural-immersion course for his future elite.
- our Torah tends to give us principles rather than detailed courses of action; and we have to think hard about how the principles apply in any given situation.”
- there is no mention of protest,
    * Honouring the emperor.
- the ancient Babylonians were clever architects and skilled engineers, and their drive to build the most impressive buildings on earth found its outlet in a succession of emperors, notably Nebuchadnezzar. And through the centuries it has been the same, with the drive to push buildings higher into the heavens as potent images of human achievement:
    * Religion has tried to achieve this too. God has destroyed these structures in the past.
- Nola Passmore, a psychologist, puts it well: The heart cry of the human race is for meaning and purpose, a sense of belonging when human relationships fail to satisfy, a need to know we are unconditionally loved in spite of our circumstances, a need to know that we are not an accident of chance but people of design, a need to know that we have a future and a hope even when everything around us seems to be falling apart.
- The question “Who am I really?” is one of the deepest questions we can ask.
    * In Christ we have these things.
    * We try and test philosophies over many years trying to determine what is the optimal way. Who am I? What is human nature? The answer is revealed in Christ.

**5. The Resolution and the Protest**

- Daniel tells us that the elite students like himself and his friends were trained for three years in a broad curriculum, involving the languages and literature of the Babylonians.
    * This probably involved studying their religions and mythologies. This was going into the culture and not enforcing there own culture on the place. The same with John the Baptist. The emperor was on good terms with John even when he had him locked up for upsetting others.
- It was, therefore, God’s prohibition that made the food unclean, which raises the question as to why the food laws were instituted in the first place. Why not simply speak of the need to avoid defiling inner attitudes of mind? Paul gives us the answer in his letter to the Galatians. He tells us that, just as in ancient custom a child had a guardian to protect it until maturity, for Israel the law acted as a guardian until Christ came. There is a sense in which God treated the infant nation of Israel as a child, guarding it with rules and regulations for the early stages of its development.

**6. The World-View of Babylon**

- We might sum up these ancient philosophies as follows: Matter is eternal and existed before the gods. In its basic state, matter was a formless, unorganized and boundless chaos. Some god imposed order and form on the basic stuff of the universe (cosmos), and this process is what is meant by creation. Even this god, like all the others, arose out of original matter, and is part of the stuff, or one of the forces, of the universe. Everything in the universe emanates out of this god, like sunbeams out of the sun; and so, in some sense, everything is god.
- We should take careful note, however, that Daniel did not protest against the education in the University of Babylon as such. He clearly devoted himself to it, and we can well imagine that he enjoyed his university course. He and his friends put such energy into the learning of the languages, literature, philosophy, science, economics, history, and so on, that they were star pupils and ended up with the top distinctions, far ahead of the rest. Daniel did not protest as an observer outside the system: he protested as a participant.
- It is important to bear this in mind, not least when we hear the term “apocalyptic literature” being used in connection with the book of Daniel. This description tends to conjure up the idea of some wild and irrational prophet of doom, warning people to flee society, barricade themselves like monks or hermits against the world and await the imminent, all-engulfing cataclysm that marks the end of history.
- if that is what “apocalyptic” means, it clearly does not apply to Daniel or his friends.
- It is important to realize this, since in the New Testament no distinction is made between evangelism and apologetics: all evangelism involved the defence of the gospel.
- The early Christians were constantly meeting objections to their message. They were often misunderstood
- in order to clear a path for the gospel message, they had to remove the barriers in people’s minds. They did this by engaging with them, answering their questions, and defending the Christian message against misunderstanding, misrepresentation, and vilification.
    * Defended in a court the gay cake

**7. The Manner of the Protest**

- If we are to cut any ice with people we must similarly learn to be gentle and respectful towards them. It is sad that there are some Christians who seem to find these two things very difficult. It is worth analysing why that should be. For some, the conviction that they “know the truth” produces in them an aggressive attitude that reeks of superiority and is very off-putting.
- They forget that the One about whom they profess to be witnessing – he who was the truth (John 14:6) – was the most gentle of men.
- Daniel understood the responsibilities of the officials and what their fears were, and he was careful to respect their feelings.
    * Respect the responsibilities of our overseers and deal with them in gentleness and respect .
- There is a simple but important lesson here for us. Daniel took time. He was not in a frantic hurry, and he was sensitive to others’ need for space.
    * Pang of regret for not sticking it out longer than 4 years in the CoG. I was in a project that was running 1.5 years late and had little direction/structure/hope for a future. I came home to my family and saw the same thing and there was nothing I could do about it.
- There was one occasion while I was a student when I found myself at a dinner, seated beside a Nobel Laureate. I tried, as best I knew at the time, to engage him in a discussion about the reality of God. After dinner he invited me, together with some of his professorial colleagues, to his room for coffee. I was the only student present and the atmosphere was intimidating, to say the least. When we were more or less settled (less in my case) he asked me whether or not I should like to make a serious career in science. “Yes sir,” I replied. “Then give up these childish ideas of God,” he said. “They will only disadvantage you intellectually among your peers.”
- It was a defining moment. I asked him what he had to offer as a rational explanation for the universe and its laws, as an alternative to God. He surprised me then by trying to explain that some kind of “life force” was responsible. I had thought that such thinking was dead. I tried to gently point out that this appeared to me much less rational than what I already believed. I was summarily dismissed.
- A brilliant Oxford biology student told me that her teachers had said as much to her. They told her that any world-view convictions she had would only hinder her science. As if their own atheism is not a world-view!

**8. The Logical Structure of Daniel**

- we can see that the Aramaic section contains a remarkable statement written in the first person by the emperor Nebuchadnezzar. It tells how he came to acknowledge the existence and power of the one true God, and to worship him.