---
title: "Matt Chandler - Is church membership biblical?"
date: "2019-01-01"
categories: []
tags: [C-001]
typora-root-url: ../../public/
bibliography: Library.bib
draft: true
local: false
---

I'm not sure that membership is biblical. Matt Chandler wrote an article a while back. This article summarises my thoughts on the article and the topic in general. Matt felt the same way I do now and was persuaded that it is biblical. He outlines in this article what persuaded him.

Main Article -["Is church membership biblical?"]( https://www.9marks.org/article/journalchurch-membership-biblical/)

## Comments

> “The spouse of Christ cannot be adulterous; she is uncorrupted and pure. She knows one home; she guards with chaste modesty the sanctity of one couch. She keeps us for God. She appoints the sons whom she has born for the kingdom. Whoever is separated from the Church and is joined to an adulteress, is separated from the promises of the Church; nor can he who forsakes the Church of Christ attain to the rewards of Christ. He is a stranger; he is profane; he is an enemy. He can no longer have God for his Father, who has not the Church for his mother.”
> — Cyprian, *Treatise on the Unity of the Church*, 6.

He starts with a quote regarding to the body of Christ which all believers are, by default, members of. The spouse of Christ is the bride, which is the body of Christ, consisting of all true believers regardless if you are member of a church or not.

This distinction is outlined in J.J.Banks booklet, "The Church and the Churches of God"{% cite banks1883 %}. This understanding was made an emphasis by some Christian movements, namely the needed Truth party (churches of God), and it's off shoot the vernal party. Both would found their basis on this truth. The "I am of Christ party" technically were not wrong, but they used their truth as justification for a division/sub-sect of the wider local body of Christians in Corinth.

> I had a strong understanding of the church universal but wasn’t well versed—and, as I said, somewhat skeptical—about the church local.

The above expresses the current position I find myself in.

> "Highland Village First Baptist Church was a “seeker-sensitive” church in the Willow Creek mold and had no formal membership process, although they were actively working on one and wanted the new pastor’s input. I had a strong understanding of the church universal but wasn’t well versed—and, as I said, somewhat skeptical—about the church local. We started growing quickly with young and oftentimes disenchanted 20-somethings who usually had no church background, or bad church backgrounds. They liked The Village because we were “different.” This always struck me as strange because we weren’t doing anything but preaching and singing."

His comment that *"we weren’t doing anything but preaching and singing"* to me suggests that this church had an imbalance in their emphasis' when meeting together as a church. I know many churches like this in my home city, who's Sunday morning/evening is preaching and singing. Many of them chuck communition into the mix too as an optional extra. Activities like fellowship, communal prayer, are impractical in such a large church. At prayer meetings we split into smaller groups which isn't ideal as people's hearing aides go crazy. Fellowship is done afterwards where the cafe next door opens and we have the chat. I can't help feeling there is a better way though.

First of all, I think the preaching is important and having a building to preach to the group at large group is great. However, for breaking of bread, fellowship, prayer, setups like community groups are far better suited enviroment for these practices. You can add the other gifts to the mix. But we'll see how the article turns out.

## TWO QUESTIONS FROM HEBREWS 13:17

> "Two questions occurred to me. First, if there is no biblical requirement to belong a local church, then which leaders should an individual Christian obey and submit to? Second, and more personally, who will I as a pastor give an account for? ... the Scriptures clearly command Christians to submit to and honor an elder body (Heb. 13:17, 1 Tim. 5:17). Will I as a pastor be held accountable for all the Christians in the Dallas Metroplex?"

I think the first part of my answer to his question *"Will I as a pastor be held accountable for all the Christians in the Dallas Metroplex?"* is "no, just the ones under your care". Paul's instruction to look after the flock in which you have been appointed as overseers appears twice and is quite clear about that.

The second part would be to consider what the boundaries of the local sphere is. This is a difficult one so we (1) what was the pattern of the NT church? (2) how does this pattern translate to today's enviroment?

See notes on [boundary of local church sphere of NT church](bear://x-callback-url/open-note?id=B3B0E9D7-0B86-41AA-B60B-C0A2CAA8B0C2-13808-00000CB0FB4A0353)

## WHAT ABOUT CHURCH DISCIPLINE?

The writer points toward Paul's guidance on how the Corinth church were instructed to put away a man who was living in "blatant, unrepentant sexual immorality". His summary "Paul warns them that this type of wickedness shouldn’t make them boast, but rather mourn" is accurate .

> My question out of this text is simple: How can you kick someone “out” if there isn’t an “in”? … how do you remove someone from [a] community of faith?

Firstly, this letter is addressed to the whole congregation of believers in Corinth (1v2) not just the elders (…if there were any…). Secondly, 2 Cor 2 gives instruction on how to re-associate with a person. Paul states that the person was “punished by the majority” and they were to “turn to forgive and comfort him … reaffirm your love for him”. There is no mention of “accepting him back into membership”.

There to me is 3 categories of people, and 2 ways to treat them (1) a Christian who is considered of the household of faith (2) a Christian who calls himself a brother but is living in moral disobedience against God (3) a non-christian. We should (1) love them like a Christian (2&3) love them like a non-christian.

One group is in satan’s family; the other in Christ’s family.

*So then, as we have opportunity, let us work that which is good toward all men, and especially toward them that are of the household of the faith.*  (Gal 6:10)

There is an alternative solution than implementing "membership". Two questions  (1) who is Paul addressing when giving this instruction? (2) in what manner does Paul teach to re-associate with such a person? (1) the congregation (not solely the leaders) (2) affirm your love for such a person (2 Cor 2).

So this is more difficult. 1 Cor 5 the other verse about delivering a person to satan are difficult to get around. Especially the second one where an individual "delivers" a person to satan. Humans have authority to do that in a similar way we hear God delivered Job to satan.

## OTHER EVIDENCE FOR MEMBERSHIP

> Acts 2:37-47 … the church was tracking the growth (v. 47)

*The Lord added to their number* (v.47) would more likely suggest that this was the Lord adding believers to the body of christ, not the local church in Jerusalem.

Acts 6:1-6  There was leadership

Acts 6:1-6 People were elected to tackle issues

1 Timothy 5:3-16 The church was organised

---

## Summary and Conclusions

I would have liked to have see a paragraph on the main points on the otherside of the debate. I guess I’ll just have to find someone that way inclined.

A question that goes hand in hand with the topic of membership is the question of how big a church should be. I'm inclined to believe that a local company should be enough to fit in a house. I group of local companies should make up a local church. Many churches, including my current church, deal with the issue of lack of community by implementing community groups. I think this is a wise implementation.

An issue with the churches of God was that they defined the local church based on the local council definition of the boundaries of a city. The biggest area described in the NT s a church was Jerusalem at 1.5sqKm. in larger areas like Rome (which at the time was around 13sqKm), Paul breaks trend by refering to the Christians there as "the church who meet in [persons] house". Picking up the pattern from Jerusalem/Corinth and putting it into Rome was difficult due to its size. Im not suggesting that we don't go bigger than the 1.5sqKm area, but suggesting asking the question why Paul didn't refer to the Christians in Rome as the church of God in Rome?

I’m not persuaded by this article. Membership seems to me one of those "common sense" practices acting as a bandaid to fix the wider issue of dis-unity among believers. It's a practice with little scriptural basis. It is my view that the local church boundary was defined by the boundary of the immediate local community.

---

{% bibliography --cited %}
