---
title: "Church Governance"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---

Every time Paul entered a city 

When Paul found some disciples in Ephesus, he told them to be baptized into the name of the Lord Jesus and when Paul placed his hands upon them they began to speak in tongues and to prophesy. (Acts 19)

Parallel this with the Pentecost story in Acts 2:1-4. This was probably the case throughout all areas where Paul planted a church. 

I have been deprived of their fellowship. They have been deprived of mine. I still believe I am in fellowship with you, regardless if you don't believe the same. This is a default position in which God has decided. I believe the man of 1 Cor 5 to be in fellowship with the church. Just for moral disciplinary reasons, he could not practice fellowship with fellow believers. 

Fellow believers I am in fellowship with through Christ.

**Longing for church governance**

Christians historically been known to long after a human governance to tell them what to do and what to believe. It is fundamental to the organization of evangelical movements such as the Methodists, Episcopalians and Presbyterians. It's what brought around movements like Jehovah Witnesses and the Catholic Church. The Israelites were no different.

In the UK, we talk about the never ending political fight between the labour and the tories, and when appointed, rely on them to do the difficult thinking and decision making.


<!--stackedit_data:
eyJoaXN0b3J5IjpbMTI0NzM4MTU0OV19
-->