---
title: "David's Emails"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---



>  I think that Paul would roll over in his grave of he knew we were turning his letters into Torah
>
>  -- F.F.Bruce



**DM**

What is this quote supposed to mean? That the writings of Paul are less the word of God, less God's law than the books of Moses?

It kinda looks that way...

Having clicked on the post and read a little on him, he doesn't seem 
terribly liberal, really, but then that's what folks used to say about 
NT Wright...

It does seem like an odd quote. 

Neither Moses nor Paul, David nor Job, John nor any scribe would have 
thought they were good enough conduits to write the Almighty's words, 
only the Almighty himself can add the signature of his authority, and 
that he most certainly does over all scripture, none more than any 
other.



**CA**

I'm not sure the context of the quote but from my observation, many 
movements who attempt to implement the apostolic church treat their 
understanding as "Law" and deal out out consequences if they are not 
adhered to. My issue with this is Pauls letters contain many ambiguities
 where context need to be considered. The Torah was written to Israel as
 a list of "do this, do that. I am the LORD" in an undeniably crystal 
clear way. I just wonder why God chose to reveal his new law in the way 
he did through Paul's letters.



**DM**

Part of the issue is the difference between law and grace. But please do not make the mistake of having a take it or leave it/ pick and choose attitude to any of the word of God. It's a bad path to start down and will end up in no good place. Look to church history. There is no new heresy under the sun, it's all quite well documented.

**CA**

Those who know me well know I am not the "take it or leave it / pick and choose" type. I believe the guidance that Paul gives for a church is 
profitable in its entirety. My 2 main concerns are (1) is there adequate system in place to challenging the agreed understandings and change it  if required and (2) how should an individual or group be viewed if they do not adhere to the non-essentials (worship styles/eschatology/earth age/sacrement practices).

There are Christian movements who who seem to take passages which deal with dis-association with groups or individuals (e.g. 1cor5;1cor15:43;2thess3:14) and apply it to those who's understandings of non-essential doctrines do not align with their own. If Paul knew how many groups have used his letters as justification for causing rifts in the body of Christ, I feel he would be "turning in his grave".



**DM**

People don't tend to *strongly* support views that aren't terribly 
important. There is plenty room in the church already for disagreement 
on plenty tertiary and secondary issues- that is why Baptists, 
Presbyterians, brethren, Episcopalians, Methodists, etc etc can all 
agree to disagree and share fellowship with each other without falling 
out. But then if someone comes along and casts doubt on central issues 
of the faith, and remain in that error despite various warnings and 
pleadings, they can expect to be treated as outcasts, and rightly so. 
There are a few views on things that are central to the faith that 
really can't be challenged without making yourself heretic, or even 
apostate (ie outside the church) This is how groups like Jehovah's 
witnesses, Mormons, Rob bell followers, Catholics, liberals and the like
 come to be. 

I wonder what beliefs it is that you are interested in challenging?

It is difficult to interact with what you are saying when there are many things that are not clear....

I can understand some things about what you are saying, though, since 
there are indeed some groups that are much too strict on matters of 
fellowship.



**CA**

I'm intentionally being conservative with my words ;) Public forum and 
all. But I just though that may answer your question on which beliefs 
I'm interested in challenging.



**DM**

Ah. Ok, I'd be with the other team on that one. :-) Paul doesn't suggest on these matters.



**CA**

This is a topic I had to tackle quite recently and I feel I've came to a
 resonable conclusion on it. I think the New Bible Commentary's take on 1
 Cor 14:33-36 sums up my current view quite nicely.



**DM**

I think Paul puts it best, and he's actually pretty clear :-)



**CA**

So, how does the passage square with his similarly clear point 1 Cor 11:5?



**DM**

Sorry, on hols just now and I'm busy. I'm not sure what you mean there. 
Women should have their heads covered in the context of worship, that's a
 clear direction from that text. 

Where there are less clear passages, we interpret them by the more clear
 passages. If in one place it clearly and directly instructs 
"circumstance A should never happen", then in another place it *seems* 
to say "in circumstance A we should do this", then what should we do? 
The first example is direct and clear, addressing the issue head on. The
 second is not addressing the issue directly at all, but *seems* to be 
addressing it indirectly (but I'd say it isn't). 

Unless we want to be charged with trying to get away with as much as 
possible, holding the text as loosely as possible, we *don't* take the 
indirect dubious passage as excuse to *not* follow the obvious clear one
 by having the indirect passage interpret and ultimately trump the 
direct clear passage. 

I think that's clear enough, but if you need clarification on terms of a
 good example, I can do that with a little cut and paste. :-)

We are called to be faithful to the text. Not trying to get away with as much as possible.



**CA**

I feel you are thinking I'm trying to debate you which i'm not. I'm 
genuinely interested in your perspective. I don't hold my views with a 
tight fist and I'm open to careful persuasion. My question was regarding
 the percieved contradiction where Paul gives guidance on women praying 
and prophesying at church gatherings, then 3 chapters later asks women 
to be silent.



I take a non-traditional understanding and believe a women *should* be allowed to participate in prayer and prophesy



**DM**

I was not really debating so much as genuinely answering your genuine 
question of how we deal with perceived contradictions. I explained how I
 feel we should deal with them, I'm interested in how you deal with 
them. 

Perceived contradictions are often just perceived. 

I am glad we are both trying to have an open handed discussion about 
this, but obviously when dealing with these matters, as you've pointed 
out, things can get complicated so we can't just answer over-simply or 
we'd not be doing any justice at all to the issue. When stuff gets 
complicated, genuine debate often happens anyway. It's nothing to be 
afraid of, and can be profitable to all for learning and holiness. 

I'd welcome your thoughts on my points I brought up. I'd hope you're not
 dismissing discussion because it's getting complicated or discursive.

As for myself, i am entirely convinced that due to the overwhelmingly 
clear biblical commands on the issue, women should not teach in the 
church, and should be silent.  Convinced as i am, I am perfectly happy 
to discuss.



**CA**

---


