---
title: "david's emails wip"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---



"Where there are less clear passages, we interpret them by the more clear passages"

True, unless your comparing apples and oranges. 1Cor 11 deals with prophesy and prayer. 1Cor14 deals with prophesy and interpretation.

Correct me in my logic but I read into it as follows:

I agree, Paul does not deal with the topic directly in chapter 11. He's bringing it up in passing to deal with the issue of headship. From this passage, we learn that women were an active part in prayer and prophesy at some sort of level while gathered as a church in the presence of their husbands. Paul knew this and decided not to rebuke them for it at this point in his letter, but instead offered them guidance on how to do it properly. 3 chapters later, he then decided to specifically rebuke women for prophesying (no mention of prayer here), a practice he previously offered guidance on (1Cor14).

Prayer can be silent. Prophesy can't be silent

Was it the same type of prophesy?

*1cor 14:26-40*

- (v26) Addressed to "Brothers and Sisters" (NET, CSB, NIV, NLT) or "brethren" (KJV, AMP)
- (v26) hymn, lesson, revelation, tongue, interpretation
- (v27) tongue, interpretation


- (v28) interpretation, 
- (v29) prophesy, weighing what is said
- (v30) prophesy
- (v31) Addressing "all" 
- (v31) prophesy, which comes learning and encouragement
- (v32) prophesy
- *(v33) women*
- *(v34) women*
- *(v35) women*
- (v37) prophesy
- (v39) prophesy, tongues 

*1cor 11:2-16*

- (v3) headship
- (v4) prayer, prophesy, headship
- (v5) prayer, prophesy, headship
- (v6) headship
- (v10) headship
- (v13) prayer

*Col 3:16*

* (V16) teaching and exhorting one another in all wisdom, sing psalms, hymns, and spiritual songs, all with grace in your hearts to god
* ​