---
title: "Book Review: Developments in the Churches of God"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---

1892

[@luxemoore1892] 



>  "But, besides these scriptures, there are at least two [1] which cannot be included above. We refer to Acts 2:42 and 1 Cor.1:9. In both of these scriptures the word koinwnia evidently means not the act of having, acting, and suffering in common, nor yet that which is in common possessed; but rather the community of those who are partners together." ([p. 508](zotero://open-pdf/library/items/GGL2U5AW?page=257))

*After going in to great depth of each of the 19 uses of instance of the use of a list of reference to the 19 instances where the word In the foot notes he brings in 2 Cor 9:13 as a proof text to make his point. Everyone who has the son in common, is in mutual fellowship with each other in the Son (note on p.508)*

 The writer claims as a proof text 2 Cor 9:13.

> [1] "We say "at least," for possibly a few of the above-named—e.g. 2 Cor.9:13—should rather be put into this category." ([p. 508](zotero://open-pdf/library/items/GGL2U5AW?page=257))



> **2 Corinthians 9:13** (ESV) By their approval of this service, they will glorify God because of your submission that comes from your confession of the gospel of Christ, and the generosity of your contribution for them and for all others,



> "our English word "community" means not only the having in common, but also they who have in common." ([p. 509](zotero://open-pdf/library/items/GGL2U5AW?page=258))

*For instance, the writer states this point which demonstrates this. This is the exact concept expressed by in 1 John 1:3. (note on p.509)*



1954 & 1981