---
title: "elders and deacons"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---



----



http://www.bible.ca/ntx-elders-pastors-bishops.htm



[@aitken1986]

[@hickling2016]



**VI. The Limit of the Elder's Authorit**y

**A. Elders authority in the Bible was limited to within one local congregation:** 

1. ​

2. Acts 20:28 "Be on guard for yourselves and for ALL THE FLOCK, AMONG WHICH the Holy Spirit has made you OVERSEERS, to SHEPHERD the church of God which he purchased with His own blood."

3. 1 Pet 5:1-3 "Therefore, I exhort the elders AMONG YOU ... shepherd the FLOCK OF GOD AMONG YOU ... proving to be examples to the flock"

4. 1 Pet 5:1 "I exhort the elders among you, as your fellow-elder"

   1. Fellow-elder: Either meant he was a elder just like them (e.g. I'm a dad to my children just like you are a dad to your children) OR
   2. He was held the joint office of elder of the church he was writing to
   3. Option 1 would be the common sense understanding. It would be difficult to argue for understanding 2

5. Peter was an elder but he was not higher in rank that any other elder.

6. All elders in the eldership are of equal authority.



**B. Many churches today do not follow the Bible pattern for an elder's authority:** 

1. ​

2. One bishop/elder is never over other bishop/elders in rank: all are equal. 

3. One bishop/elder is never over more than one local church churches

4. The pyramid type organization is contrary to the Bible pattern and did not come to full development until 606 AD when pope Boniface III claimed to be the one man who ruled every local church world wide. This was 600 years too late to be the Bible pattern and represents a serious apostasy in organization.



**C. The Baptist church, for example, admits in their official creed book (The Hiscox Standard Baptist Manual), that new offices not found in scripture have been added long after the Bible was written:**

1. ​

2. "CHURCH OFFICERS: In the New Testament we find that in apostolic times, and for many years after, pastors and deacons only were known as permanent church officers. Others have been added at later times, for a variety of reasons." (The Hiscox Standard Baptist Manual)

3. "THE WIDER FELLOWSHIP OF BAPTISTS: Because churches are the only Christian organizations provided for in the New Testament, it may be said that they are the only ones really essential to the accomplishment of the purposes of Christ. Experience, however, has demonstrated that churches in fellowship with one another are able to fulfill the work of the gospel more effectively than churches alone." (The Hiscox Standard Baptist Manual)

4. What we observe in these two quotes from the Hiscox Standard Baptist Manual, is the following: First, they admit that new offices were added to the church many years after the Bible was completed. Second, they admit that local churches with no organizational tie between them, was the Bible pattern, but because of human wisdom, an organization was invented to tie local churches together on a global basis. 



**An elder can only oversee one local congregation** 

1. ​

2. Each church is self governing and autonomous

3. A bishop from one church can not oversee another church



**D. Churches in the Bible began with no elders but in time elders were appointed**

1. ​

2. Churches can scripturally exist either with or without elders

   1. a church without elders because no one qualified: Acts 14:1-3,6,8,21-23
   2. a church with no elders, when qualified men could be appointed, "lacks": Tit 1:5



---

