---
title: "Email to Steve"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---

Acts 2:42 the fellowship (an activity) vs 1 Cor 1:1-9 The Fellowship (the entity)**

> "The reference in Acts 2:42 does not refer to ‘the Fellowship’ (an entity), it refers to ‘fellowship’, an activity which was to characterise those who having heard the word preached by the apostles, had believed, were baptised, and had been added to the growing number of like-minded people at that time. The activity of ‘fellowship’ was to sit alongside another three core activities which these first post-Pentecost disciples of the Lord Jesus were to devote themselves to, namely, the apostles teaching, the breaking of the bread and the prayers. I have attached an article (written by yours truly) recently published in Needed Truth that hopefully helps with the understanding of what the act of ‘fellowship’ involves (note that this is a draft and differs a bit from what was finally published)"



> "Paul & his companions are writing to the group of disciples in Corinth at that time who clearly are addressed as ‘the church of God in Corinth’. By the time we get to v9, we learn that these disciples had been ‘called you into [the] fellowship with [of] his Son Jesus Christ our Lord’. Note my insertion of the definite article ‘the’ before ‘fellowship and the ‘of’ instead of ‘with’. This is actually in the original Greek, is curiously left out of many modern translations (including my favourite NIV). It is important to note that the definite article does not appear in the Greek in Acts 2:42."



> "So we see two distinct expressions involving fellowship, one is an activity (Acts 2:42), the other is an entity (1 Cor 1:9)."



On your understanding of Acts 2:42, it's interesting as this hasn't been the historical understanding from almost all Needed Truth writers (see examples from from Luxemoore[@luxemoore1892], Stoope[@stoope1954] & Bassey[@bassey1981] who all state clearly that the use of 'fellowship' in *both* 1 Cor 1:9 *&* Acts 2:42 is in refererence to the collective 'entity'). Infact, Luxemoore's article would further claim 2 Cor 9:13 to be in the same category (I assume this would be . The earliest article I've found to align with your view would be G. Neely's article in the 2002 Needed Truth.[@neely2002]

This seems to be a development on a proof text which supports a key principle in Churches of God thinking.   which the writer states that both 1 Cor 1:9 & Acts 2:42 are both proof texts for the concept of 'The Fellowship' (entity).

​		

​	From a brief survey of needed truth articles over the last 125 years, the pattern seems to have moved from understanding the use of fellowship in Acts 2:42 was an 'entity' (e.g. Needed Truths from 1892, 1954 & 1981) to agreeing that this was infact describing an 'activity' (e.g. G.Neely, Needed Truth 2002). The later I would agree with.

They would all agree with you that the key text for understanding 'The Fellowship' as an 'entity' is found in 1 Cor 1:9 has consistently maintained its position as the key verse though all the needed truth writings ive read when supporting the understanding of "the Fellowship" as an entity. However, I feel they have neglected to consider the direct parallel in 1Jn1? I guess bible translators would agree with that line of thought considering the overwhelming majority of them remove "the" to make the parallel with 1Jn 1 clearer. The use of the definite article can easily be explained but pointing out there is only one Christ, so in joining with him, we are all joining the same fellowship.

Additionally, in the context of the passage (1Cor 1:1-9 ) is a thanksgiving to *God* for the work *He* has done through Christ. He describes his recipients as: (a) *sanctified in Jesus Christ*; (b) *called to be saints, with all those in every place who call on the name of our Lord Jesus Christ, their Lord and ours*; (c) possessing the *grace of God*; (d) *will be blameless on the day of our Lord Jesus Christ*; (e) being *strengthened…till the end* and; (f) *called into [the] fellowship with[of] his son*.

These are attributes gifted by God that all granted by the work on the cross, and gifted when each individual had been called to accept this truth. Understanding the final statement as *called into fellowship with his son* as a further we are called into the universal church (the body of Christ). This sticks with the whole theme the opening passage (if not the whole theme of the scriptures!) and again I believe this is quite obvious.

**Worldwide United Elderhood & the Acts 15 The Jerusalem Council**

> "Their responsibility is ‘global’ i.e. an overseer in one assembly as part of the united elderhood world-wide and is therefore recognised as an overseer in any church of God he may move to."

> "There is no New Testament evidence of churches of God existing in isolation – quite the opposite; churches are linked by a common elderhood who strive for unity – as per the Acts 15 model."





Apart from the understanding of the events and the resultant letter from the Jerusalem council in Acts 15, what other evidence in scripture is their to support a worldwide united elderhood?

It's difficult to do a proper review of the CoG agreed understandings  The needed Truth articles don't hold any authority, onlyauthorative letters written following the overseers conferences are not available online. it would be good to have a place where I could view all these letters written. all I have to go on is opinions of the needed Truth publications, which are no Authorative and it has been stated in the publications that these do not reflect the view of the movement   

**Recognition and Removal of Overseers**

> "[Overseers] are recognised by local overseers in fellowship with overseers in the district ... The removal of men from deacon or oversight service happens in the same way: deacons at a local assembly level and overseers at a district level."

How is this practice supported scripturally? I see the office of overseer was an office recognised in each church by Paul, Barnabas and Titus (the later given a list of attributes to look for), but I can’t think of any mention of them seeking approval from a council of overseers.

**Acts 20.17-38 Pauls Swansong to the Ephesian Elders**

> "overseers have a responsibility before the Lord to [maintain the unity of the Fellowship] – see Paul’s dialogue with the Ephesus overseers in Acts 28 – particularly v28-38, a very moving ‘swansong’ from the apostle to his beloved fellow-elders."

**1 Cor 5:13 The Wayward Man**

**1 Cor 11:16 Churches of God have no other practice**

> "Cor 11:16 ... demonstrates in a kind of casual way the reality of common practice throughout all the churches of God."



> "You also get it very strongly in Acts 15 which was arguably the first conference of overseers. Their objective was to debate a controversial issue, discern the Spirit’s leading and then roll out the consequent decision/practice through all the churches of God by means of a letter which would be circulated amongst them."

See note on Acts 15:1-35.

**2 Cor 2:5-11 Forgive the sinner**

**Matt 16; Eph 1:13; 2:8; John 10:27-30; John 3:16  Body of Christ**

**1 Pet 1:1-2**

**1 Tim 3:14-15 Church of the Living God**

**Other Comments**

> "An interesting point here is that when the present COG movement came into existence in the 1890s, there was very clear evidence of the movement of the Holy Spirit amongst groups of disciples who seemed to be simultaneously convicted about the truth and somehow found each other. Amazing – given how limited communication was in those days!"

The strength of Open Brethren which we came from still runs today. They have a very strong culture of conferences and inter-church fellowship. From what I have read, the influence of the needed truth's understandings was quite an insignificant influence. I think it was only about 5% of the churches joined the movement, then following the "Vernal" strand in the early 1900s when the moevemt lost 50% of the Scottish assemblies. This was a really interesting read. There was an article about this 

> "deacon responsibility for a specific church that does not necessarily transfer from one church to another"

**Concluding Remarks**

To me there just seems to be a lot of missing information to support these understandings. Paul writes in 1Cor 4:6 "I have applied all these things to myself and Apollos for your benefit, brothers, **that you may learn by us not to go beyond what is written**, that none of you may be puffed up in favor of one against another." I feel many of these understandings go beyond what is written, elevating 'common sense' to the same level as prescription.
