---
title: "Email Tips"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---



## [EOM]--End of Message

One of the biggest time wasters with email is the need to actually open the email to read the message. Although it might not seem much, repeated hundreds of times a week, it's quite a time burden--especially if you're working on a cell phone or other portable device.

If you can convey the entire message in less than, say, 60 characters, put the whole message in the subject line, and close the subject line with [EOM]. That way, your recipient knows everything he or she needs to know without even opening the email.

For example, this email with just a subject line and no body:

SUBJECT LINE: Weekly review is at 3 p.m. in Conference Room 3 [EOM]

...is much better than the usual email that looks something like:

SUBJECT LINE: Weekly review meeting
BODY: This week's weekly review meeting will be held in Conference Room 3.

## [NRR]--No Reply Required

A stronger version than the old standby FYI (For Your Information), NRR (No Reply Required) makes it explicit that you do not require a reply to this email.

Once someone can see--from the subject line--that there is no "response overhead" in reading the email, it's much more likely to get opened and acted upon. E.g.:

SUBJECT LINE: Agenda attached for weekly review [NRR]
[Y/N]--Yes/No Question

Most people can attack a yes/no decision with more alacrity than something more complicated or multifaceted. If you just need to know if someone wants chicken or fish, or whether 3 p.m. works better than 4 p.m., use [Y/N] to get your answer more quickly. E.g.:

SUBJECT LINE: Decision needed on location of weekly review [Y/N]
BODY: Do you want to meet at Starbucks or in the conference room?

## [RB+ ]--Reply By (insert timeline)

Need a reply by tomorrow? Tell the recipient up front by putting [RB+1] in the subject line. A week from now = [RB+7], a month = [RB+30], etc. Need it today? [RB+0]. An hour from now? [RB+0.1]. E.g.:

SUBJECT LINE: Will you be attending the weekly review? [RB+2] [EOM]

## [AB+ ]--Action By (insert timeline)

Works the same way as Reply By, except that this code alerts the recipient that there is an action embedded somewhere in the email that he or she needs to take by a certain date/time. E.g.:

SUBJECT LINE: I need the agenda for next week's weekly review [AB+5] [EOM]

These two codes together are incredible productivity promoters, as they can be used by the recipient to plan needed activities in advance.

## [PYR]--Per Your Request

If you're sending someone something previously asked for (in other words, your email isn't initiating any new actions), let the person know right up front. E.g.:

SUBJECT LINE: Agenda attached for weekly review [PYR]

The bottom line: Don't wait until the weight of email "unreads" produces the inevitable dropped ball or missed deadline--or worse, the need for total email "amnesty." Establish and implement your own set of email subject-line protocols today.

[sauce](http://www.inc.com/les-mckeown/3-simple-letters-that-will-increase-your-email-productivity-immediately.html)