---
title: "GV Statement of Faith"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---



**1. In the divine inspiration, authority and sufficiency of the Bible**

**2. That God exists eternally in three persons – Father, Son and Holy Spirit to whom equal honour is due**

**3. That Jesus Christ, unique Son of God, became man, being begotten of the Holy Spirit and born of the virgin Mary**

**4. That he died for our sins, was buried and rose again for our justification**

**5. That he ascended to the right hand of God and is now the all-sufficient High Priest of His people**

**6. That he personally will return to receive his people and judge the world in righteousness**

**7. That man has fallen and needs the Holy Spirit’s work in regeneration and sanctification**

**8. That man may be restored to repentance towards God and faith in the Lord Jesus Christ**

**9. That at death the soul of man does not cease to exist or become unconscious**

**10. That the dead will be raised either to life or condemnation and that the blessedness of the righteous and the punishment of the unrighteous will, alike, be eternal**