---
title: "Inductive Study Approach"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---



Inductive Study Approach

To facilitate "hearing" God's Word as you study, this approach employs three basic, sequential techniques:

- Observation
- Interpretation
- Application



**OBSERVATION:** Teaches you to see what the passage says and is the basis for accurate interpretation & correct application. Observation answers the question, "What does the passage say?"

Step 1: **Begin with prayer**

Step 2: **Ask the "5Ws & an H"**

- **Who** is speaking? Who is this about? Who are your main characters? To whom are they speaking?
- **What** is the subject or event covered in the chapter? What do you learn about the people, event or teaching?
- When do/will the events occur or did/will something happen to someone in particular?
- **Where** will this happen? Where was is said? Does this location have a relevent past or future mention in scripture?
- **Why** is something being said or mentioned?  Why would/will this happen? Why at the time/to this person/in that place? 
- **How** will it happen? How is this to be done? How is it illustrated?

Step 3: **Mark Keywords and Phrases**

Step 4: **Look for Lists**

Step 5: **Watch for Contrasts and Comparisons**

Step 6: **Note Expressions of Time** (Don't forget "until", "then", "when", and "after")

Step 7: **Identify terms of conclusion** ("Wherefore", "finally", "for this reason", "therefore", "so", etc.)

Step 8: **Develop Character Themes** (Ignore the ones printed in your bible and instead write in the margin what YOU think the theme is, centering on the main person, event, teaching or subject of Scripture. (Sometimes themes actually begin in the previous chapter and/or end in the subsequent chapter.)



**INTERPRETATION:** Answers the question "What does the passage mean?"

Follow these basic rules:

1. Remember that context always rules first
2. Always seek the ful council of the Word of God (Compare and contrast similar passages)
3. Remember scripture will never contradict scripture
4. Don't base your convictions on an obscure passage of scripture
5. Interpret scripture literally
6. Allegories and typology are used to illuminate & confirm, never to replace & create
7. The NT has priority



**APPLICATION:** Answer the question, "What does it really mean to me personally? What truths can I put into practice? What changes should I make to my life?"

