---
title: "Long Distance Relationships"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---



1. **We both know each other's schedules and have set our expectations accordingly**
2. **We trust each other**
3. **We found a way to "hang out" remotely**

Tips:

* Schedule (1-2) phone calls a week via skype at specific times. If one can make it, rearange for another night that week.
  * **Decide** a time to have a long, uninterrupted/non-distracted chat (find a pub/coffee shop if house is full). This will work as a booster and will help you cherish each other’s choices and delights. I feel insecure if I find out there is more than one other person at the otherside and will be less trusting/open in my conversation.
  * Provides feeling of security to both parties
  * The onus is on the party who cancelled to set the new time
  * All other conversations (whatsapp/other phone calls) have no pressure to respond
  * Reduces the risk of resentment of feeling like the other party has no time to speak when **you** want to speak
  * We like each other because we both pursue interesting lives. If our communications get in the way of out daily lives then we will have little interesting stuff to say!
	* We like each other for our individual interests and passions - nursing, church, bible study, family, friends, career. I want you to be 100% present when your engaged in them.
  * Reduce the frequency to 1 time a week if it is distrupting life.
* Both be 100% open. If there is something on our mind, don't keep it in to conserve the other persons feelings. Harder in the short term, but better in the long run.
  * If you dont like something I said, tell me.
  * Dont lie. If we accidentally lie, don't feel bad about confessing and correcting yourself. E.g. I will sometimes over exaggerate a story to make is seem more interesting that it is (you have 47 sisters right??)
  * Never use the silent treatment
* When not in our schedules phone call, life is more important (unless something important comes up). If a text takes 2 days to respond to, either party should ne feel resentment.
* Do house work while in conversation
* Send postcards / letters
* Go dating
  * Start a 2 person book club
  * watch a series
* **never go more than six weeks without seeing one another in person**
* Call and text each other during the day
  * This wont be possible with my workload. I would sometime turn my phone on airplan mode so I can focus on my work/study/friends.



https://www.bustle.com/articles/144152-how-to-survive-a-long-distance-relationship-when-youre-terrible-on-the-phone

https://interpersonal.stackexchange.com/questions/4087/how-should-i-address-scheduling-phone-or-video-calls-with-my-long-distance-girlf

https://www.huffingtonpost.co.uk/entry/how-to-survive-a-long-distance-relationship\_us\_58c96c4ae4b0934e249cbed4?guccounter=1