---
title: "Markdown Style Guide"
date: "2018-01-01"
categories: []
tags: []
typora-root-url: ../../public/
bibliography: Library.bib
draft: true
---



To be used for discussions via blog/email/facebook etc.



# Good Practice: Writing and Quoting Numbered Lists

The format of the lists below are to be used when creating or quoting list of points. This allows you to break up a list into individual quotes in your response without the markdown auto numbering having any effect. The bold type works well in google docs where if you bold the title, is creates a title on google docs,



*Writing lists*

**5. This the title of the point**

This is the description of the first point

**6. This is the title of the next point**

This is the description of the next point



*Quoting Lists*

> **5. This is the title of the point**
>
> this is the description of the point
>
> **6. This is the title of the next point**
>
> This is the description of the next point

My comment to above list points

> **7. Title of Further point**
>
> Description of further point

Comment on the is further point





## Bad Practice: Writing and Quoting Numbered Lists

The following formats should be avoided. The automatic numbering of numbered lists.



*Creating Lists*

1. This is the first item in the list 

2. The next item in the list is created by hitting "Enter"

   I am using Ctrl + Enter to create the next line to add a further description of the

   You can create multiple paragraphs with this method

3. For this lineI used Shift + Tab and wrote "1." to create the next list item



*Quoting Lists*

> 1. The next item in the list is created by hitting "Enter"
>
>    I am using Ctrl + Enter to create the next line to add a further description of the
>
>    You can create multiple paragraphs with this method
>
> 2. For this lineI used Shift + Tab and wrote "1." to create the next list item