---
title: "Greenview Chairing Notes"
date: "2018-01-01"
categories: []
tags: []
typora-root-url: ../../public/
bibliography: Library.bib
draft: true
---

**Pre-start**

- [ ] Preacher: Colin Adams
- [ ] Video: Check if there is a video
- [ ] Song Leader: Mike
- [ ] Prayer Team: Ian Macdonald, Nicki Adams
- [ ] Offering: Which ministries?

**Inclusive Welcome**

- Name
- Welcome
- Glorify God
- Acessability for all
- Familiarity and variety

**Brief Highlighted Notices**

1. **This mornings service** - final part of Exodus 40 with Colin Adams

2. **Evening service @ 6** - final part of Philippians with Allan McKinnnon

3. **Prayer meeting @ Thursday night**  - with TearFund

4. **Christmas is coming card** - with various Christmas/New year services. Please use to invite.

5. **Christmas in Song..for seniors** - A new event for Greenview for those over 60. I’d stress that this an evangelistic service so bring a neighbour or friend if your able. Anyone under 60 -  why not "grab a granny" - bring an older neighbor / friend / family member? 

6. **Christmas Hampers** - for people in need. Give donations to Grace Wylie. Testimonies of some of the recipients of the hampers at our CAP service a few Sundays ago it does make a difference.

7. **Hogmanay Bash** - help needed for food, games, ceilidh and service. Please speak to an elder.

8. **Giving** - will be an opportunity to give financially later n the service for the various ministries at Greenview

**Opening Prayer**

- the tabenacle priests "singers harps, loud-sounding cymbles, raising sounds of joy"
- We are all priests and preistesses to God, with Christ as our high preist

**Singing:** "Come Thou Long Expected Jesus" / "What Hope we Hold This Starlit Night" / "Joy Has Dawned Upon The World"

**Scripture Reading or Appropriate Video**

- Glorify God

**Actual Reading or Video Item**

- Glorify God

**Offering Hymn: O Little Town of Bethlehem**

- Direct stewards
- Sunday School / Creche will leave AFTER offering hymn while band play on
- Offering an opportunity for those who are regular attendees to give to the various ministries of the Church
- Visitors, great to see you along, and not expected to contribute to our efforts here at Greenview
- Glorify God

**Children Leave**

**Prayer**

- Christmas themed introduction
- Unrest in Paris
	- Authorities would manage things well
	- Pray for the safety of the protesters and the police
	- Easy to destroy, difficult to build up
- We will soon be discussing the ark of the covenant
	- we learn in you word that you required alot of effort from your people to preserve the ark, dealing out consequences if it was not handled properly
	- Reflecting on this  increases our amazement that you had given us an infinately more precious possesion
	- A vesse more precious than the Ark
	- Who's birth we will be celebrating over the next few weeks
	- One whom humans tried to destry
	- But praise God, the grave could not hold him
	- We don't fully understand what kind of love lead you to give us your only son, a people who had done nothing to deserve it, but we who have accepted it, are eternaly grateful.
- We pray for opportunites in the next few weeks through festivities to share this good news
	- We are thankful for the freedom in this to share this country
	- There are countries not quite to blessed
- Prayer for children and Sunday School leaders who leave
- Prayer for upcoming sermon / speaker and response
	- It won't be the manner of the presentation that captures our attention, but it would be the word of God it's self that holds the power.
	- Gifted teachers possessing a gift from God, and being faithful spirit led presenters of Your word.
	- Thank you for giving teachers like Colin this gift and the heart to pursue this gift
- We thank you for the other gifts in this community of believers and ask for blessing in the various minsitries they are part of 
- We pray that the offering given this morning would go to furthering these ministries
- Glorify God

**Sermon**

- Colin Adams (Exodus 40)

**Singing:** "From The Squaleor Of A Borrowed Stable"

**Prayer Team announcement**

- Opportunity for prayer up the front
- Prayer team: Ian MacDonald, Nikki Adams
- Speak to the person next to share what they they were encouraged by during the sermon or the songs. It may be an encouragement to you and you may have an encouraging word for them
- Closing verse
- 1 Thessalonian 4:9-10 
- "Now about your love for one another we do not need to write to you, for you yourselves have been taught by God to love each other. And in fact, you love all of God's family throughout Macedonia. Yet we urge you, brothers and sisters, to do so more and more"
- How does he suggest we do this? By encouraging each other with words (v18)
- Specifically words that remind each other of the work of Christ, looking forward to the full fulfilment of God's promises through him when "will meet the Lord in the air" (v17)
- It's also struck me recently me how that God is pleased with being reminded of his promises by his people and especially being reminded of his Son. If god seeks reminders, how much more might we benifit from being reminded.
- Glorify God

**Closing Benediction / Prayer**

- Open up to the congregation
- Time of silence
- Glorify God