---
title: "Is a Non-Denominational Church a Denomination?"
date: "2018-01-01"
categories: []
tags: []
bibliography: Library.bib
typora-root-url: ../../public/
draft: true
---



## Suggested alternative Titles (ordered by Preference)

All local churches have their own distinctives, therefor all local churches are their own denomination.

* Independent
* Local Branch (of the Churches of God)
* Local Denomination
* Local Autonomous Branch (of the Churches of God)

The Vernalites had the right Idea, but were still cursed with 

Christians

What Christendom recognises as a Denomination would be a group with a system of governance outwith the local church. What they would recognise as non-denominational would be. This is just an arguement of 

Definition of Terms

A better way of re-establishing 

This needs a bit of wisdom and an autonomously governed church and a bit of wisdom (two things which were lacking in my old branch).

Ok the simple rule is, if you can interchange the term "denomination" with "christian branch", then you were in a denomination.

People get upset if I use denomination. They get upset if I use sect. It's like the whole gay marraige thing again. But I guess the guidance is not using the title for what it is. Just use the definition.

I get in arguments with my dad about the use of the word "denomination". Any attempt to define the Churches of God as a "denomination" was met with your a denomination.

So I thought I'd do a bit of research and come up with a method of clearing this up. First, I should create a methodology in which to come to my conclusion. First step would be to choose a reliable authority. In the UK, we have 3 widely used dictionaries.

1. Collins Dictionary
2. Oxford English Dictionary (OED)
3. Cambridge English Dictionary

From a scholarly standpoint, the OED dictionary, which uses "more than 3.5 million quotations" is considered the most trusted authority for defining english words. To simplify things a bit, lets use the concise english 

What the internet says...

> The OED is a historical dictionary and very different from dictionaries of current English where the focus is on present-day meanings. It contains the history of each word, and of the language, traced through more than 3.5 million quotations, from classic literature and specialist periodicals to film scripts and cookery books.

> From a scholarly standpoint, though, honestly, the OED dictionary is the only English dictionary that I would even consider to be an option.

So lets only use the Oxford english dictionary. Lets create a statement that says "According to the Oxford Dictionary..."



https://en.oxforddictionaries.com/

*Derogatory terms*

These terms are derogatory in todays english language and should be used sparingly in the risk of getting people backs up.

1. **Sect** A group of people with somewhat different religious beliefs (typically regarded as heretical) from those of a larger group to which they belong.

Although the terms may accurately describe the group, using a term which is considered derogatory is unwise.

*Non-derogatory*

1. **Splinter group (or party)** A small organization, typically a political party, that has broken away from a larger one.
2. **Division** Difference or disagreement between two or more groups, typically producing tension
3. **Branch** A division or office of a large business or organization, operating locally or having a particular function.
4. **Denomination** A recognized autonomous branch of the Christian Church

According to the Oxford English Dictionary:

**Denomination** A recognized autonomous branch of the Christian Church
**Branch** A division or office of a large business or organization, operating locally or having a particular function.

Do non-denominational churches believe they are a recognized autonomous organization which has a particular function of the Christian Church?

- Answer:  No/Yes (it's complicated) - A non-denominational church is an autonomously governed church (singular) which is not under any ecclesiastic organization out with the local church. Of course, the local church in its self would have its own governance, but you wouldn't call this an "organization"


Do the Churches of God (Charity no. 299106) believe they are a recognized autonomous organization which has a particular function of the Christian Church?

- Answer: No - They believe they are the tree. Although they have all the distinctives of a denomination, they do not belive they fulful a particular function of the Christian Church, but are in fact THE Christian Church to exlusion of all other christian group.

Do the Jehovah Witnesses believe they are a recognized autonomous organization which has a particular function of the Christian Church.

- Answer: No - They believe they are the tree. Although they have all the distinctives of a denomination, they do not believe they fulful a particular function of the Christian Church, but are in fact THE Christian Church to exlusion of all other christian group.

Do churches linked with a denomination (PCA/OPC/Southern Baptist) believe they are a recognized autonomous organization which has a particular function of the Christian Church?

- Answer: Yes - a denominational church is a denomination. They believe there is no issue with a heirarchy of governance and their denominational branch fulfils a function of the overall Christian Church in their particular region (America/England/Scotland).

Is Brethren/Baptist/Presbyterian/Epicopalian a denomination?

- Answer: No (Technically) - its a tradition. Presbytarian and Episcopalian are examples of 

Is 


The problem is this - some branches think they are the tree. 

The most accurate term is the english language which would describe the Churches of God is "denomination". There is no argument here. Any attempt at bringing this up would fingers pointed at "non-denominational" churches.

Are non-denominational churches a denomination?

Is the Churches of God a denomination? Yes

I believe Paul was very careful with his use of analogies. If he wanted to use "tree" he would have, but instead, to describe the universal church, he used "body". When he described the preisthood, he used "house". The significance of these two analogues is that there is only one of them.

Are autonounsly governed local churches a denomination?

Accordning to the oxford english dictionarys definition of a denomination as being a branch of christianity, to be considered a denomination, they would have to be considered a "branch of Christianity". 

A division or office of a large business or organization, operating locally or having a particular function.


Non-denominational churches may adopt a movements distinctives (Baptist, Plymouth Brethren, Restoration Movement, Hebrew Roots) but as their purpose is not to sprout new local churches which are under the authority of a branch, then they cannot be considered a branch (i.e a tree branch). Therefore, non-denominational is the correct use of the term. They may affiliate them selves with movement distinctives (Baptist, Plymouth Brethren, Restoration Movement, Pentecostal) or a statement of faith (5 solas, Wesminister, Baptist) but they do not affiliate themselves with a denominational branch.



We have 

Splinter group
Sect
Division
Denomination

Denomination is not a helpful term. 


https://docs.google.com/drawings/d/18yjbbPCsClSudmZ15Sbn1ouvKY7oVOtYsYKFyZDk4RI/edit