---
title: "Steve's Email"
date: "2018-01-01"
categories: []
tags: ["@seddon2018"]
typora-root-url: ../../public/
bibliography: Library.bib
draft: true
---

Email sent 25th May 2015

Steve Seddon to Chris Aitken

Hi Chris.

I finally get down to spending some quality time on your questions; thanks for your patience.

I thought it best to deal with your points one by one (your point in green, my response in blue):

*At a meeting of what were known as the elders of Great Britain, the following six points were laid down to be accepted by all:*

Who/what is the source of this quotation?

*1. There is on earth a unique concrete thing (called in Acts 2:42 "the Fellowship") which consists of all those whom God has brought together in a visible unity; the being in this is conditional. It is quite distinct from the Body of Christ, the church of Matthew 16.*

The reference in Acts 2:42 does not refer to ‘the Fellowship’ (an entity), it refers to ‘fellowship’, an activity which was to characterise those who having heard the word preached by the apostles, had believed, were baptised, and had been added to the growing number of like-minded people at that time. The activity of ‘fellowship’ was to sit alongside another three core activities which these first post-Pentecost disciples of the Lord Jesus were to devote themselves to, namely, the apostles teaching, the breaking of the bread and the prayers. I have attached an article (written by yours truly) recently published in Needed Truth that hopefully helps with the understanding of what the act of ‘fellowship’ involves (note that this is a draft and differs a bit from what was finally published)

The term ‘the Fellowship’ as used to describe the entity that comprises all churches of God around the world, is a scriptural term, however, Acts 2:42 is not a reference that helps our understanding of this concept; 1 Corinthians 1:9 is a key reference for this. Here it is in context:

**1 Corinthians 1:1–9** Paul, called by the will of God to be an apostle of Christ Jesus, and our brother Sosthenes, To the church of God that is in Corinth, to those sanctified in Christ Jesus, called to be saints together with all those who in every place call upon the name of our Lord Jesus Christ, both their Lord and ours: Grace to you and peace from God our Father and the Lord Jesus Christ. I give thanks to my God always for you because of the grace of God that was given you in Christ Jesus, that in every way you were enriched in him in all speech and all knowledge— even as the testimony about Christ was confirmed among you— so that you are not lacking in any gift, as you wait for the revealing of our Lord Jesus Christ, who will sustain you to the end, guiltless in the day of our Lord Jesus Christ. God is faithful, by whom you were called into the fellowship of his Son, Jesus Christ our Lord.

So Paul & his companions are writing to the group of disciples in Corinth at that time who clearly are addressed as  ‘the church of God in Corinth’. By the time we get to v9, we learn that these disciples had been ‘called you into [the] fellowship with [of] his Son Jesus Christ our Lord’. Note my insertion of the definite article ‘the’ before ‘fellowship and the ‘of’ instead of ‘with’. This is actually in the original Greek, is curiously left out of many modern translations (including my favourite NIV). It is important to note that the definite article does not appear in the Greek in Acts 2:42. So we see two distinct expressions involving fellowship, one is an activity (Acts 2:42), the other is an entity (1 Cor 1:9). Even today, the name used by churches of God in any legal document is taken from 1 Cor 1:9. We are ‘The Churches of God in the Fellowship of the Son of God, Jesus Christ our Lord’ – a bit of a mouthful, but nevertheless scriptural.

Staying with Corinthians for the moment, we learn several more relevant things:

(-) Disciples were ‘called by God’ (1 Cor 1:9) into the Fellowship – something which is amazing to me (you get it emphasised in several other places too, a favourite of mine is 1 Pet 1:1-2)

(-) A disciple’s place in a church of God can be forfeited as a consequence of certain sins – hence it is conditional. Sexual sin is one of these and is illustrated in 1 Cor 5:13 where the Corinthian church is instructed to ‘expel the wicked man from among you’. Thus, unlike the church the Body of Christ, from which it is impossible to be removed (Matt 16; Eph 1:13; 2:8; John 10:27-30; John 3:16 etc..), it is possible to be removed from a church of God.

(-) A disciple who has been ‘expelled’ from a church of God, once repentant, can be restored. 2 Cor 2:5-11 shows what happened to the wayward man of 1 Cor 5 – he was repentant and restored.

Chris, perhaps these points are a help to at least provide some direction to question 1. Obviously there is a lot more that could be said.

*2. The Fellowship finds its expression in churches of God; and the churches are linked together in the Fellowship.*

This is demonstrated through the Acts of the apostles and the epistles of the New Testament. 1 Cor 11:16 is an interesting snippet which demonstrates in a kind of casual way the reality of common practice throughout all the churches of God. You also get it very strongly in Acts 15 which was arguably the first conference of overseers. Their objective was to debate a controversial issue, discern the Spirit’s leading and then roll out the consequent decision/practice through all the churches of God by means of a letter which would be circulated amongst them.

*3. The existence of the present Fellowship does not admit of a church of God coming into existence except in connection with the already formed churches.*

There is no New Testament evidence of churches of God existing in isolation – quite the opposite; churches are linked by a common elderhood who strive for unity – as per the Acts 15 model. That said, I suppose it is possible for a group of Christians, who see the truth of the Fellowship of the churches of God, but are not aware of us (COG’s today) so could set up their own community. The reality is there have been some churches that have seen the truth and have subsequently applied to join us. This is often how the churches first came to being in The Philippines, Malawi, Kenya and other places. There are others under review in central Africa as we speak. 

An interesting point here is that when the present COG movement came into existence in the 1890s, **there was very clear evidence of the movement of the Holy Spirit amongst groups of disciples who seemed to be simultaneously convicted about the truth and somehow found each other**. Amazing – given how limited communication was in those days!

- This truth your refer to i assume is in reference to the understanding of the Fellowship as a singular entity.
- I understand a very similar system had already been implemented many years previous which had brought about the (so called) 'Exclusive Brethren' quite a few years before in 1948.
- The 'Circle of Fellowship' as is was refered to was described as "a joint body of mutually approved assemblies, with the decision of one binding on all" [@piepkorn1970 p. 3]
- The churches of God would differ from this where rather than one local church making decisions binding on all churches, it would be the overseers meeting which would be binding by all.
- The Exclusive Brethren system seem almost identical to the Catholic Church system.
-  The Vatican City church working as one unit, a council of overseers in that local church making decisions, and having a spokesman anouncing the general mind of the council.
- This decision is now binding on all churches in their Circle of Fellowship (aka. [Communion](https://en.wikipedia.org/wiki/Communion_(religion)]))
- Darby's teachings an that of his his associates would have been quite influential throughout the 1800s

*4. It is the bounden duty of every man exercising over sight in the Fellowship to do his utmost to maintain the unity of the Fellowship.*

Sure, overseers have a responsibility before the Lord to do this – see Paul’s dialogue with the Ephesus overseers in Acts 28 – particularly v28-38, a very moving ‘swansong’ from the apostle to his beloved fellow-elders.
\5. Does the responsibility to receive into or put out from the circle of overseers reside in the circle of overseers in a town, or in that of a county or district?

The practice is as follows:

(-) Deacons are recognised at a church level and have deacon responsibility for a specific church that does not necessarily transfer from one church to another. This is a really interesting topic and one which we (overseers) in the North West are reviewing amongst ourselves to explore bow this practice can be supported from scripture.

(-) Overseers are made by the Holy Spirit (Acts 20:28), and are recognised by local overseers in fellowship with overseers in the district. Their responsibility is ‘global’ i.e. an overseer in one assembly as part of the united elderhood world-wide and is therefore recognised as an overseer in any church of God he may move to.

(-) The removal of men from deacon or oversight service happens in the same way: deacons at a local assembly level and overseers at a district level.

While the concept of a united elderhood is clearly supported from scripture, some of the practicalities are really driven by common sense. For example, the scriptural support for a smaller group of ‘leading brethren’ may be tricky to support from scripture, however in a global community that has say 300 overseers, a smaller leadership group within the 300 is expedient – to lead the leaders, if you get my gist. This point is contentious even amongst some overseers, but from my perspective it is simply common sense.

*6. When overseers in a given circle have a difficulty in becoming of one mind in the Lord, the next larger circle of overseers should come in to assist in producing the desired oneness of mind."*

This probably overstates the reality a bit. It is the global conference of overseers that meet together to discern the Spirits leading for a scripture-based position on doctrine and practice throughout the churches (Acts 15). There is no latitude for any given assembly or district to come up with its own rules on any given issue (if you think about it, this would be a recipe for ‘anarchy’ – each church/district having the freedom to do its own thing). That said, there are occasions when brethren in a local church may struggle to manage a situation and would seek fellowship from the local district to help clarify the ‘official position’ on a topic and understand its practical outworking.

Also, what other differences would the Churches of God have the conservative open-brethren movement (e.g. the Gospel Halls) out with the 6 points mentioned? It would bbe good to discuss those things too.

My understanding (which is very limited) of conservative open-brethren practice in relation to the things in earlier questions is that they are pretty autonomous – there is no effective global elderhood with leadership responsibility across the entire movement. On this basis, there is no vision/conviction about the importance of unity globally and therefore no infrastructure to support it.

Chris, a banner that hangs over all of the above, particularly the last point, is the vision and passion the Lord Jesus Himself has for unity amongst His disciples as expressed in His prayer in John 17. A deep study of this prayer will reward you richly. Your questions are great and if your heart is sincere (I believe it is) in wanting to discern the Lord’s will for your service, He will reveal to you the truth of churches of God and make it precious to you. That was my prayer for you as I sat down to try to help you with these questions.

If you are still with me brother, thank you for your stamina in getting through my verbiage – I hope and pray there is something of value here for you. Please let me know & keep the dialogue going eh…

For your information and prayer, Tom is off to Dundee on June 4th for an interview to do a masters in forensic archaeology and anthropology – how cool!

Much love brother,

@seddon2015