---
title: "10 Reasons For Leaving"
date: "2018-01-01"
categories: []
tags: []
typora-root-url: ../../public/
bibliography: Library.bib
draft: true
---

In 2018, at the age of 31, I had descided to part ways the the Churches of God movement. This was not an easy decision and one I will be.

I had grown up in this movement and had came to faith through the summer youthwork programs they ran at a camp near Kilmacholm. I attended universi



*Distinctives of the churches of God*

**They take historical needed truth understandings over main steam scholars**

Comparitive studies are key to understanding the context of a passage



**misenterpretation of the “the flock” as referring to the “whole flock”**

Apart from the obvious parallel verse, there is no scriptural prescribed system of ecclesiastical authority system out with the local church.



*Distinctives of the Plymouth Brethren movement*

**The divisive mindset**

The Plymouth Brethren movement has been a divisive movement with the 'leave your church because we more accurately teach and practice the truth' mindset. Protestant Christianity throughout the years been cursed with this divisive mindset which has caused major , but movemebts like the Plymouth Brethren movement and the CoG seem to be the main culprates.

The CoG movement seems to have adopted this divisive attitude as one of their primary distinctives.

I've learned that there are movements with a unity mindset who see the idea of 'encouraging partnerships' of Philipians 1:5. Non-profit organisations like 'FIEC' and 'the west of Scotland partnership' are 2 examples which are set up to encourage each other in the gospel without holding any ecclesiastical authority.

rather than 'join us or your not a true church'.



**The title the “Churches of God”**

This may seem like a strange one to have on the top of my list. I mean, it is the biblical description used in the majority of the letters (1Cor 1:2; 

Paul taught specifically against this mindset. He even specifically rebukes a group with a similar party slogan

*What I mean is that each one of you says, “I follow Paul,” or “I follow Apollos,” or “I follow Cephas,” or “I follow Christ.” Is Christ divided?*
— 1Cor 1:12-13a

Many commentators attribute most of the issues attribute the majority of the issues in the first letter to the Corinthian church to this this “I follow Christ” group. One commentators comments they seemed to believe they had an exclusive relationship with Jesus Christ that the other groups didn’t possess. In my study into various divisive movements (LDS, JWs, CoC etc,) many have the common theme of calling them selves the Church of Christ/Jesus Christ/Worldwide Church of God/

If you apply that title only to your movement, then you are in danger only applying it within you bubble, neglecting the rest of the body of Christ which it must be applied to. Over the last 200 years, we have seen many 'restorationism' movements who have come out of the "2nd great awakening". Many tired of sectarian christianity made a move to restore the pattern of the early apostolic church. Movements such as and later the Jehovah Witnesses, and Plymouth Brethren. These movements addopted the terms 'Church of Christ' (stone-campbell movement), 'Church of Jesus Christ' (LDS), 'Worldwide Church of God' (Armstrongism), 'Church of God' (Adventists), 'Church of Christ' (original name for the JW movement), 'Church of God' (Black Hebrew Israelites). These are all well known divisive groups, the majority of which have written off mainstream christianity.

Some of the the similar distincives of these movements are

- Rejection and disassociation from mainstream Christianity
- Non-trinitarian*

*It must be noted that the churces of God do no way reject the trinity and are very much in agreement that the Jesus was God manifest in the flesh, and that the holy spirit is the 3rd pesrson of the Godhead. They do however adopt the Plymouth Brethren underrstanding worship should be only addressed to the Father. If the Son or Holy spirit is addressed, it must be in the context of the full God-head. One of of the key starters of the movements expressed this view in the article 'Paul on Worship' written by one of the early leaders of the movement, C.M. Luxemoore. The same writer around the same time collated the 'psalms, hymns and spiritual songs', the hymn book which is used in the movements formal meetings to this day.





---



# 10 reasons why I left the church




*Not reasons for leaving*

**The lack/decline in number**

Noah kept faith regardless of the fact that no-one but his family listened to him. If I was convicted that what we had in our movement was true, I would have stayed regardless of the numbers

**Individuals in the church**

I love and respect all those in the church of God and have appreciated their patient time, prayer and hard work they have put into me though out the years. Many of those men are not in the movement any more, but many still are and are a still continued help and support. You have demonstrated by your friuts that you are of God.



*Distinctives of the churches of God*

**they would take historical needed truth understandings over main steam scholars**

Comparitive studies are key to understanding the context of a passage. I have been exploring various understandings of mainline biblical scholars who. To refer solely back to needed truth articles for our understandings of passages suggest we believe that there are no worthwhile insights in biblical interpretation in the last 100-110 years are worth pursuing is a grave mistake. This is from observation but is also supported by the fact we still maintain our 

Do we truly believe that any new insights will solely come from within our movement? What about the rest of the body? Paul teaches that those members of the body we consider less honourable we below with greater honor. Writing off all christians who do not 100% align with our unserstandings in all aspects of doctine is a damaging and divisive mindset. A mindset that Paul wrote against in 1 Corinth.

We live in a very different environment and parts of the scriptures will need to be considered. Views on the role of women in prayer, spiritual gifts. There are biblical basis for these things that we seem to write off based on our traditions and have no time for. Regardless if they are right or not, Paul’s message in 1 Corinth seems to say there is more important things than being right. Namely unity for the sake of the Gospel to include all believers who are not walking in moral disobedience against God.

To write off a whole group of christians because they don’t share your doctrinal positions is an unbiblical divisive mindset that I believe Paul to be directly addressing in his letter. When I worked in Edinburgh, I had the opportunity to join a friend at his Wednesday evening bible studies at a gospel hall church. I attended the bible study for almost 3 years and had gotten to know the movement very well and the beliefs they held, even witnessing a breaking of bread service. What I discovered is that the differences between the two movement were the width of a hair. One had the bread and wine at the beginning, the other at the end. They used slightly different phrases in their prayers and teaching which demonstrated their theological differences. Behind the scenes, there would be a difference in how a church go about recognising elders if moving from another church, but nothing you would see unless part of the oversight.

The key thing that I noticed that, (1) they had maintained the traditional understanding of the gospel hall movement despite having no ecclesiastical authority outwit the local church (2) the do not have ‘informal’ meetings unless meeting at each others houses.

The lack of informal meetings resulted in a more consistent practice throughout all their church meetings including their family services, Sunday schools, gospel meetings, conferences. All meetings were considered suit & tie, female head coverings/silence, no instruments, .

The CoG churches have distinct ‘formal’ and ‘informal’ meetings. Their informal conferences (YFR, YPM, Convention 242) and local meetings (gospel meetings, family services, , many the biblical principles were relaxed (headcoverings, instruments,). The informal meetings and conferences quite often would emphasis the importance of the formal meeting, giving  guidance on how to prepare our thoughts for the Sunday morning worship, learning new songs to use on the Sunday morning, teaching on the importance of head coverings in church (taught by a women not wearing a head covering).

I don’t want to emphisis this “formal vs informal” distinction too much but I just want to use it as a demonstration that the differences between the formal meetings are about the width of a hair

They had leadership conferences, but the decisions reached in these conferences were not authoritive.


**Emphasis on the house of God teachings**

This is made manifest by the overwhelming majority of the elders and teachers. Its emphised at conferences, ministries, bible studies and in our Sunday morning worship.







*Distinctives of the Plymouth Brethren movement*

**The divisive mindset**

The Plymouth Brethren movement has been a divisive movement with the 'leave your church because we more accurately teach and practice the truth' mindset. Protestant Christianity has been cursed with the mindset following the step away from the RCC movement, but movemebts like the Exclusive Brethren, Churches of God, Churches of Christ  seem to take this one step further by asking christians to come out of their gospel preaching churches and join them in the ‘restored church’.  The CoG movement seems to have adopted this divisive attitude as one of their primary distinctives in a different way. From what I’ve learned about the early days of the movement, they put the call out to all churches to come under their ecclesiastical structure, and would reject any church which refused to joined with them as not a true church as they did not fall under the biblical pattern for ecclesiastical authority.



The Plymouth Brethren movement has been a divisive movement with the 'leave your church because we more accurately teach and practice the truth' mindset. Protestant Christianity has been cursed with the mindset, but movemebts like the Plymouth Brethren movement and the CoG seem to be the main culprates.

The CoG movement seems to have adopted this divisive attitude as one of their primary distinctives.

I've learned that there are movements with a unity mindset who see the idea of 'encouraging partnerships' of Philipians 1:5. Non-profit organisations like 'FIEC' and 'the west of Scotland partnership' are 2 examples which are set up to encourage each other in the gospel without holding any ecclesiastical authority.

rather than 'join us or your not a true church'.



**misenterpretation of the “the flock” as referring to the “whole flock”**

Apart from the obvious parallel verse, there is no scriptural prescribed system of ecclesiastical authority system out with the local church.



*Summary*

[Summary of the reasons for leaving]

[Summary of the solution I’ve chosen instead and advice for those part of the movement]

I've learned that there are movements with a unity mindset who see the idea of 'encouraging partnerships' of Philipians 1:5. Non-profit organisations like 'FIEC' and 'the west of Scotland partnership' are 2 examples which are set up to encourage each other in the gospel without holding any ecclesiastical authority.

Reconsider the understandings of “The Fellowship” and “The Flock” as individual churches. 

rather than 'join us or your not a true church'.

**The name the “Churches of God” title**



Paul taught specifically against this mindset. He even specifically rebukes a group with a similar party slogan:

> *What I mean is that each one of you says, “I follow Paul,” or “I follow Apollos,” or “I follow Cephas,” or “I follow Christ.” Is Christ divided?*
> — 1Cor 1:12-13a

Many commentators attribute most of the issues attribute the majority of the issues in the first letter to the Corinthian church to this this “I follow Christ” group. One commentators comments they seemed to believe they had an exclusive relationship with Jesus Christ that the other groups didn’t possess. In my study into various divisive movements (LDS, JWs, CoC etc,) many have the common theme of calling them selves the Church of Christ/Jesus Christ/Worldwide Church of God/

Restorationism movements (2nd great awakening)
[Restorationism - Wikipedia](https://en.wikipedia.org/wiki/Restorationism)
Worldwide Church of God; Church of God, International (non-trinitarian; binitarian)
LDS - church of Jesus christ
Stone-campbell - church of christ
7th Day Baptist and Adventist - Church of God

Distincives

- Rejection and disassociation from mainstream Christianity
- non-trinitarian (churches of god do not reject the trinity but take a strong stance on the recipient of the worship should be solely the father and not the son/Holy Spirit . The son/Holy Spirit can be worshiped but only in the context of the godhead)



Test [@book{banks1994paul]







[@aitken1986]

[@mohler2018]

[@mohler2018a]