---
onnexiatitle: "YF Notes: The Partial Kingdom - Bible Study"
date: "2018-11-04"
categories: [yf_notes]
typora-root-url: ../../public/
bibliography: Library.bib
csl: ios-press-books.csl
draft: true
---

## Exodus 19:1-13; 20:1-17

### 19:1-13

**What does this passage teach us about God?**

.(v10-11) It takes 2 days of concecretion for us to even see God. Even then, he will come conceiled in a thick cloud.

.(v12) Touching where is presence was would lead to instant death. Even at Israel's most consecrated state, they were not holy enough to touch the ground he stood in

**How should we relate to such a God?**

.Through a worthy mediator. Moses was a good mediator for Israel. Jesus is better

**What does he promise to do in the future?**

.Provide a mediator (a king)

### 20:1-17

**Why should we want to obey the Ten Commandments as Christians?**

.

**Which do you find especially hard to obey? What practical steps can you take to obey these commands?**

.

## 2 Samuel 7:1-17

**What does David want to build (verses 1-2)?**

. *He want's to build a house made of cedar for the LORD to dwell*

**But what does God want to build (verse 11)?**

. *(v5) "Would you build me a house to dwell in?" The question expects a negative answer. (V7) The LORD has never asked for a house of cedar.*

.*(v11) The LORD will make a house*

**How does Jesus fulfil these promises? (See Matthew 1:1; John 2:18-22; Acts 2:24-36)**

.*He is "Son of David" (Matt 1:1), who had raised up the temple (his body) (Jn2:21),*

.*and was exalted at the right hand of God (Acts 2:33)*