---
title: "YF Notes: The Partial Kingdom (Bible Study Passages)"
date: "2018-11-04"
categories: [yf_notes]
typora-root-url: ../../public/
bibliography: Library.bib
csl: ios-press-books.csl
draft: true
---

### PASSAGES: Bible Study

---

**Exodus 19:1–13** On the third new moon after the people of Israel had gone out of the land of Egypt, on that day they came into the wilderness of Sinai. They set out from Rephidim and came into the wilderness of Sinai, and they encamped in the wilderness. There Israel encamped before the mountain, while Moses went up to God. The Lord called to him out of the mountain, saying, “Thus you shall say to the house of Jacob, and tell the people of Israel: ‘You yourselves have seen what I did to the Egyptians, and how I bore you on eagles’ wings and brought you to myself. Now therefore, if you will indeed obey my voice and keep my covenant, you shall be my treasured possession among all peoples, for all the earth is mine; and you shall be to me a kingdom of priests and a holy nation.’ These are the words that you shall speak to the people of Israel.” So Moses came and called the elders of the people and set before them all these words that the Lord had commanded him. All the people answered together and said, “All that the Lord has spoken we will do.” And Moses reported the words of the people to the Lord. And the Lord said to Moses, “Behold, I am coming to you in a thick cloud, that the people may hear when I speak with you, and may also believe you forever.” When Moses told the words of the people to the Lord, the Lord said to Moses, “Go to the people and consecrate them today and tomorrow, and let them wash their garments and be ready for the third day. For on the third day the Lord will come down on Mount Sinai in the sight of all the people. And you shall set limits for the people all around, saying, ‘Take care not to go up into the mountain or touch the edge of it. Whoever touches the mountain shall be put to death. No hand shall touch him, but he shall be stoned or shot; whether beast or man, he shall not live.’ When the trumpet sounds a long blast, they shall come up to the mountain.”

**Exodus 20:1–17** And God spoke all these words, saying, “I am the Lord your God, who brought you out of the land of Egypt, out of the house of slavery. “You shall have no other gods before me. “You shall not make for yourself a carved image, or any likeness of anything that is in heaven above, or that is in the earth beneath, or that is in the water under the earth. You shall not bow down to them or serve them, for I the Lord your God am a jealous God, visiting the iniquity of the fathers on the children to the third and the fourth generation of those who hate me, but showing steadfast love to thousands of those who love me and keep my commandments. “You shall not take the name of the Lord your God in vain, for the Lord will not hold him guiltless who takes his name in vain. “Remember the Sabbath day, to keep it holy. Six days you shall labor, and do all your work, but the seventh day is a Sabbath to the Lord your God. On it you shall not do any work, you, or your son, or your daughter, your male servant, or your female servant, or your livestock, or the sojourner who is within your gates. For in six days the Lord made heaven and earth, the sea, and all that is in them, and rested on the seventh day. Therefore the Lord blessed the Sabbath day and made it holy. “Honor your father and your mother, that your days may be long in the land that the Lord your God is giving you. “You shall not murder. “You shall not commit adultery. “You shall not steal. “You shall not bear false witness against your neighbor. “You shall not covet your neighbor’s house; you shall not covet your neighbor’s wife, or his male servant, or his female servant, or his ox, or his donkey, or anything that is your neighbor’s.”

**2 Samuel 7:1–17** Now when the king lived in his house and the Lord had given him rest from all his surrounding enemies, the king said to Nathan the prophet, “See now, I dwell in a house of cedar, but the ark of God dwells in a tent.” And Nathan said to the king, “Go, do all that is in your heart, for the Lord is with you.” But that same night the word of the Lord came to Nathan, “Go and tell my servant David, ‘Thus says the Lord: Would you build me a house to dwell in? I have not lived in a house since the day I brought up the people of Israel from Egypt to this day, but I have been moving about in a tent for my dwelling. In all places where I have moved with all the people of Israel, did I speak a word with any of the judges of Israel, whom I commanded to shepherd my people Israel, saying, “Why have you not built me a house of cedar?” ’ Now, therefore, thus you shall say to my servant David, ‘Thus says the Lord of hosts, I took you from the pasture, from following the sheep, that you should be prince over my people Israel. And I have been with you wherever you went and have cut off all your enemies from before you. And I will make for you a great name, like the name of the great ones of the earth. And I will appoint a place for my people Israel and will plant them, so that they may dwell in their own place and be disturbed no more. And violent men shall afflict them no more, as formerly, from the time that I appointed judges over my people Israel. And I will give you rest from all your enemies. Moreover, the Lord declares to you that the Lord will make you a house. When your days are fulfilled and you lie down with your fathers, I will raise up your offspring after you, who shall come from your body, and I will establish his kingdom. He shall build a house for my name, and I will establish the throne of his kingdom forever. I will be to him a father, and he shall be to me a son. When he commits iniquity, I will discipline him with the rod of men, with the stripes of the sons of men, but my steadfast love will not depart from him, as I took it from Saul, whom I put away from before you. And your house and your kingdom shall be made sure forever before me. Your throne shall be established forever.’ ” In accordance with all these words, and in accordance with all this vision, Nathan spoke to David.