---
title: "YF Notes: The Partial Kingdom (Talk Passages)"
date: "2018-11-04"
categories: [yf_notes]
typora-root-url: ../../public/
bibliography: Library.bib
csl: ios-press-books.csl
draft: true
---

### TALK: Passages

**Genesis 12:1–3** Now the Lord said to Abram, “Go from your country and your kindred and your father’s house to the land that I will show you. And *I will make of you a great nation*, and *I will bless you* and make your name great, so that *you will be a blessing*. I will bless those who bless you, and him who dishonors you I will curse, and *in you all the families of the earth shall be blessed*.”

**Genesis 15:1–6** After these things the word of the Lord came to Abram in a vision: “Fear not, Abram, I am your shield; your reward shall be very great.” But Abram said, “O Lord God, what will you give me, for I continue childless, and the heir of my house is Eliezer of Damascus?” And Abram said, “Behold, you have given me no offspring, and a member of my household will be my heir.” And behold, the word of the Lord came to him: “This man shall not be your heir; your very own son shall be your heir.” And he brought him outside and said, “Look toward heaven, and number the stars, if you are able to number them.” Then he said to him, “So shall your offspring be.” *And he believed the Lord, and he counted it to him as righteousness.*

**Genesis 17:21** But I will establish my covenant with Isaac, whom Sarah shall bear to you at this time next year.

**Genesis 22:6–8** And Abraham took the wood of the burnt offering and laid it on Isaac his son. And he took in his hand the fire and the knife. So they went both of them together. And Isaac said to his father Abraham, “My father!” And he said, “Here I am, my son.” He said, “Behold, the fire and the wood, but where is the lamb for a burnt offering?” Abraham said, *“God will provide for himself the lamb for a burnt offering, my son.”* So they went both of them together.

**Ephesians 2:8–9** For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.

**Genesis 25:23** And the Lord said to her, “Two nations are in your womb, and two peoples from within you shall be divided; the one shall be stronger than the other, the older shall serve the younger.”

**Romans 9:10–13** ... when Rebekah had conceived children by one man, our forefather Isaac, *though they were not yet born and had done nothing either good or bad*—in order that God’s purpose of election might continue, *not because of works but because of him who calls*— she was told, “The older will serve the younger.” As it is written, “Jacob I loved, but Esau I hated.”

**Romans 3:20** For by works of the law no human being will be justified in his sight, since through the law comes knowledge of sin.

**Galatians 3:24** So then, the law was our guardian until Christ came, in order that we might be justified by faith.

**Matthew 5:19** Therefore whoever relaxes one of the least of these commandments and teaches others to do the same will be called least in the kingdom of heaven, but whoever does them and teaches them will be called great in the kingdom of heaven.

**Hebrews 10:10-12, 19–20** And by that will we have been sanctified through the offering of the body of Jesus Christ once for all. And every priest stands daily at his service, offering repeatedly the same *sacrifices, which can never take away sins.* But when Christ had offered for all time a single sacrifice for sins, he sat down at the right hand of God ... Therefore, brothers, *since we have confidence to enter the holy places by the blood of Jesus, by the new and living way that he opened for us through the curtain, that is, through his flesh,*

**Joshua 21:43–45** Thus *the Lord gave to Israel all the land that he swore to give to their fathers.* And they took possession of it, and they settled there. And *the Lord gave them rest on every side* just as he had sworn to their fathers. Not one of all their enemies had withstood them, for the Lord had given all their enemies into their hands. *Not one word of all the good promises that the Lord had made to the house of Israel had failed; all came to pass.*

**Genesis 3:15** I will put enmity between you and the woman, and between your offspring and her offspring; he shall bruise your head, and you shall bruise his heel.”

**Genesis 49:10** The scepter shall not depart from Judah, nor the ruler’s staff from between his feet, until tribute comes to him; and to him shall be the obedience of the peoples.

**Judges 21:25** In those days there was no king in Israel. Everyone did what was right in his own eyes.

**1 Samuel 8:5–7** and said to him, *“Behold, you are old and your sons do not walk in your ways. Now appoint for us a king to judge us like all the nations.”* But the thing displeased Samuel when they said, “Give us a king to judge us.” And Samuel prayed to the Lord. And the Lord said to Samuel, “Obey the voice of the people in all that they say to you, for they have not rejected you, but *they have rejected me from being king over them.*

**Deuteronomy 17:14–15a, 18-20** *“When you come to the land that the Lord your God is giving you, and you possess it and dwell in it and then say, ‘I will set a king over me, like all the nations that are around me,’ you may indeed set a king over you whom the Lord your God will choose.* ... “And when he sits on the throne of his kingdom, he shall write for himself in a book a copy of this law, approved by the Levitical priests. And it shall be with him, and he shall read in it all the days of his life, that he may learn to fear the Lord his God by *keeping all the words of this law and these statutes, and doing them*, that his heart may not be lifted up above his brothers, and that he may not turn aside from the commandment, either to the right hand or to the left, so that he may continue long in his kingdom, he and his children, in Israel.

**2 Samuel 7:12–16** *When your days are fulfilled and you lie down with your fathers, I will raise up your offspring after you, who shall come from your body, and I will establish his kingdom.* He shall build a house for my name, and I will establish the throne of his kingdom forever. I will be to him a father, and he shall be to me a son. When he commits iniquity, I will discipline him with the rod of men, with the stripes of the sons of men, but my steadfast love will not depart from him, as I took it from Saul, whom I put away from before you. And your house and your kingdom shall be made sure forever before me. Your throne shall be established forever.’ ”
