---
title: "YF Notes: Philippians 2:12-18"
date: "2018-10-28"
categories: [yf_notes]
typora-root-url: ../../public/
bibliography: Library.bib
draft: true
---

## Passage

**Philippians 2:12–18** Therefore, my beloved, as you have always obeyed, so now, not only as in my presence but much more in my absence, work out your own salvation with fear and trembling, for it is God who works in you, both to will and to work for his good pleasure. Do all things without grumbling or disputing, that you may be blameless and innocent, children of God without blemish in the midst of a crooked and twisted generation, among whom you shine as lights in the world, holding fast to the word of life, so that in the day of Christ I may be proud that I did not run in vain or labor in vain. Even if I am to be poured out as a drink offering upon the sacrificial offering of your faith, I am glad and rejoice with you all. Likewise you also should be glad and rejoice with me.

## Commentaries

**12** *work out your own salvation with fear and trembling.* "To say that one is working *at* a problem implies that the outcome is in doubt. To say that one is working *out* a problem suggests that it is being resolved." [@klein2017 p. 783] 

"Paul is not here concerned with the eternal welfare of the soul of the individual ... [t]he individual believer is not now being called to self-activity, to the active pursuit of the will of God ... to a personal application of salvation ... The entire church, which had grown spiritually ill (2:3–4), is charged now with taking whatever steps are necessary to restore itself to health, integrity, and wholeness" [@hawthorne2004 p. 755]

---


