---
title: "YF Notes: The Partial Kingdom"
date: "2018-11-04"
categories: [yf_notes]
typora-root-url: ../../public/
bibliography: Library.bib
csl: ios-press-books.csl
draft: true
---

## INTRODUCTION

* I've printed off all the passages that I will be refering to so you don't have to look them up. Try your best to follow along. I'll refer to the passage references as I go.

**Genesis 12:1–3** Now the Lord said to Abram, “Go from your country and your kindred and your father’s house to the land that I will show you. And **I will make of you a great nation**, and **I will bless you** and make your name great, so that **you will be a blessing**. I will bless those who bless you, and him who dishonors you I will curse, and **in you all the families of the earth shall be blessed**.”

- As a reminder in **Gen 12** God made a promise with Abraham. He promises that Abraham would have decendants, that he would reach the promised land, that there he would recieve blessing and kings would come from him which would be a blessing to the nations under them
- Tonight, we will be covering  around 1200 years spanning from Abraham to Solomon so alot to sqeeze in. We see partial fulfilment of these promises.
- The aim is to not get lost in the detail but rather to see the sweep of the bible story line. I will stop at some important details which I don't want you to miss.

## GOD'S PEOPLE

### Abraham and Isaac

**Genesis 15:1–6** After these things the word of the Lord came to Abram in a vision: “Fear not, Abram, I am your shield; your reward shall be very great.” But Abram said, “O Lord God, what will you give me, for I continue childless, and the heir of my house is Eliezer of Damascus?” And Abram said, “Behold, you have given me no offspring, and a member of my household will be my heir.” And behold, the word of the Lord came to him: “This man shall not be your heir; your very own son shall be your heir.” And he brought him outside and said, “Look toward heaven, and number the stars, if you are able to number them.” Then he said to him, “So shall your offspring be.” **And he believed the Lord, and he counted it to him as righteousness.**

* It is important to note that there was nothing particulary special about Abraham that he or his decendedants that they deserved these promises.
* In **Gen 15** it is revealed that Abraham "believed in the Lord, and he counted it to him as righteousness" 
- "He was accepted by God, not on the basis of his own Goodness but by faith in the promises of God [@roberts2012 p. 55]
- We can also tell from this passage that Abraham seems to have a bit of a problem. He and his wife are very old and have no children to carry on Abraham's name

- Abraham and Sarah decide to take matters into their own hands and Abraham takes Sarah's maid, Hagar, as a wife who bears Arbraham a son.

**Genesis 17:21** But I will establish my covenant with Isaac, whom Sarah shall bear to you at this time next year.

- In **Gen 17**, God makes it clear here that His people will not rise from Hagar's son, but from a son born to Sarah as per the original plan
- By taking Hagar as a wife, Abraham demonstrated that he did not have trust God's plan.
- However, true to God's promise, Sarah conceives and bears Isaac on her old age.
- When Isaac had grown up, God commands Abraham to take Isaac up to the mountain and sacrifice him on an altar

**Genesis 22:6–8** And Abraham took the wood of the burnt offering and laid it on Isaac his son. And he took in his hand the fire and the knife. So they went both of them together. And Isaac said to his father Abraham, “My father!” And he said, “Here I am, my son.” He said, “Behold, the fire and the wood, but where is the lamb for a burnt offering?” Abraham said, **“God will provide for himself the lamb for a burnt offering, my son.”** So they went both of them together.

- This time, if we look in in **Gen 22**, we see that Abraham demonstates a change in attitude. He walks Isaac up the mountain with out protest.
- "He knew that the future of the promises depended on Isaac's survival" [@roberts2012 p. 62]
- "there is now ... [a] confidence in the Lord, who will provide" [@sailhamer2017 p. 651]
- True to his promise, God provides a ram.
- Abraham had to learn, if the gospel had to be fulfilled, only God could bring it about.
- Abraham names the mountain "the Lord will provide" as a tribute

**Ephesians 2:8–9** For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.

- Paul reminds us in **Ephesians 2** that we are saved though faith in that it is trusting in God's work that brings about salvation. It is important to remember this.

### Jacob and Esau

**Genesis 25:23** And the Lord said to her, “Two nations are in your womb, and two peoples from within you shall be divided; the one shall be stronger than the other, the older shall serve the younger.”

- **Gen 25** Isaac grows up and marries Rebekah who gives birth to 2 sons, Esau and Jacob.
- The scheming Jacob recieves his father's blessing as though he was not the first born
- Jacob doesnt deserve that privilege. He tricks his brother out of his birth right.
- Jacob means 'holder of the heal'. Twice he held his brother back.

**Romans 9:10–13** ... when Rebekah had conceived children by one man, our forefather Isaac, **though they were not yet born and had done nothing either good or bad**—in order that God’s purpose of election might continue, **not because of works but because of him who calls**— she was told, “The older will serve the younger.” As it is written, “Jacob I loved, but Esau I hated.”

- Paul in **Romans 9** comments on this account "though they were not yet born and had done nothing either good or bad ... not because of works but because of him who calls"
- "If we are Christians today, it's not because we are better than anyone else; it's simply because [God chose us]" [@roberts2012 p. 63]
- It's imporant to remember this as you see the in present time and in history, humans will find any way to feel inferior to others. We need to learn not to be like that.
- God later names Jacob 'Israel' which means "God Strives" as a reminder it is by God's effort, not ours.

## GOD'S RULE AND BLESSING

### God's Law

- You'll' notice that the law is not yet established. Yet, Abraham is considered righteous. This is an important order. Salvation comes before the Law.

- God, through Moses, set up the system of the Law. The Law signifies God's rule. Following this law will bring blessing.

**Romans 3:20** For by works of the law no human being will be justified in his sight, since through the law comes knowledge of sin.

**Galatians 3:24** So then, the law was our guardian until Christ came, in order that we might be justified by faith.

**Matthew 5:19** Therefore whoever relaxes one of the least of these commandments and teaches others to do the same will be called least in the kingdom of heaven, but whoever does them and teaches them will be called great in the kingdom of heaven.

- What God's Law does is
	- reveals our Sin (**Romans 3**)
	- reveals our saviour (**Galatians 3**)
	- reveals his standards (**Matthew 5**)
- "God's law is not intended to be the means by which anyone gets right with God ... He redeems them before they recieve the law ... The Law reveals God's standard" [@roberts2012 pp. 69-70]
- This is fortunate as it's clear early on that Israel are unable to keep this law

### God's Presence

**Hebrews 10:10-12, 19–20** And by that will we have been sanctified through the offering of the body of Jesus Christ once for all. And every priest stands daily at his service, offering repeatedly the same **sacrifices, which can never take away sins.** But when Christ had offered for all time a single sacrifice for sins, he sat down at the right hand of God ... Therefore, brothers, **since we have confidence to enter the holy places by the blood of Jesus, by the new and living way that he opened for us through the curtain, that is, through his flesh,**

- In Exodus 25 onwards, we learn about the tabernacle. This was a place where God could set up a sacrifical system to partially clean them enough to allow Israel to be in his presence, despite their sin.

- The writer of the letter in **Hebrews 10** in teaches us that these sacrifices never trully took away sin
- Leviticus details the ceremonial acts which needed to take place. This involved lots of animal sacrifice.
- Only one man could enter the most Holy place and only once a year.
- This was not a pleasent system. Not only that, the Animal sacrifices were never trully sufficient and it's why they had to do it day after day.

- **Hebrews 10** reminds us as Christians to be thankful we no longer have to carry out these sacrifices to enjoy fellowship with God. Christ's blood acted as a once and for all sacrifice.

## GOD'S PLACE

**Joshua 21:43–45** Thus **the Lord gave to Israel all the land that he swore to give to their fathers.** And they took possession of it, and they settled there. And **the Lord gave them rest on every side** just as he had sworn to their fathers. Not one of all their enemies had withstood them, for the Lord had given all their enemies into their hands. **Not one word of all the good promises that the Lord had made to the house of Israel had failed; all came to pass.**

- Next we have God's place. As we learned from last time, the promised land was Canan.
- **Josh 21** reveals that God fulfils his promise of land to Israel by giving them land (but not all of it).
- They have also have rest at all 4 sides
- God's People are under God's Rule, enjoying His blessing ('rest')
- "Not one word of all the good promises that the Lord had made to the house of Israel had failed; all came to pass"

## GOD'S KING

### The Serpent crusher

**Genesis 3:15** I will put enmity between you and the woman, and between your offspring and her offspring; he shall bruise your head, and you shall bruise his heel.”

- But what of the serpent crusher of **Gen 3**?...

**Genesis 49:10** The scepter shall not depart from Judah, nor the ruler’s staff from between his feet, until tribute comes to him; and to him shall be the obedience of the peoples.

- Looking back to **Gen 49**, Israel know that it's going to be one of Judah's decendents who will be ruler over all nations forever
- Israel are still waiting for this. At this point, God has proven trustworthy with his promises.

### God's Judges

- Israel goes through a series of Judges
- In this stage of Israel's history, they go through a seemingly neverending cycle where:
  - Israel Sins
  - God Judges by Allowing them to be Defeated
  - Israel cries for Mercy
  - God provides a Judge
  - Land is at peace
  - Israel Sins
  - ...

**Judges 21:25** In those days there was no king in Israel. Everyone did what was right in his own eyes.

- At the end of the book of Judges in **ch. 21** there is a remark that there was no king in israel and each done what was right in their own eyes

### God Rejected as King

**1 Samuel 8:5–7** and said to him, **“Behold, you are old and your sons do not walk in your ways. Now appoint for us a king to judge us like all the nations.”** But the thing displeased Samuel when they said, “Give us a king to judge us.” And Samuel prayed to the Lord. And the Lord said to Samuel, “Obey the voice of the people in all that they say to you, for they have not rejected you, but **they have rejected me from being king over them.**

- However, **1 Sam 8** points out that they did infact have a king, God, but Israel had rejected Him and and saught after a human king like the other nations.
- If only we had a King like those other nations!
- They wanted what the other nations had - a human king to tell them what to do

**Deuteronomy 17:14–15a, 18-20** **“When you come to the land that the Lord your God is giving you, and you possess it and dwell in it and then say, ‘I will set a king over me, like all the nations that are around me,’ you may indeed set a king over you whom the Lord your God will choose.** ... “And when he sits on the throne of his kingdom, he shall write for himself in a book a copy of this law, approved by the Levitical priests. And it shall be with him, and he shall read in it all the days of his life, that he may learn to fear the Lord his God by **keeping all the words of this law and these statutes, and doing them**, that his heart may not be lifted up above his brothers, and that he may not turn aside from the commandment, either to the right hand or to the left, so that he may continue long in his kingdom, he and his children, in Israel.

- God anticipates this back in **Deut 17** and allows them to apoint a king of his choosing when they reach the promised land.
- In order for Israel to recieve the promised blessings, this king would have alot of responsibility on his shoulders
- God rules in his kingdom by means of a king. The blessings are reliant on that king "keeping all the words of this law and these statutes, and doing them"

### God's King and  Blessing

- in **1 Sam**, Samuel, the good judge, appoints Saul as King
- Saul sins and Samuel anoints David as his Saul's successor
- **2 Sam** David becomes King

**2 Samuel 7:12–16** **When your days are fulfilled and you lie down with your fathers, I will raise up your offspring after you, who shall come from your body, and I will establish his kingdom.** He shall build a house for my name, and I will establish the throne of his kingdom forever. I will be to him a father, and he shall be to me a son. When he commits iniquity, I will discipline him with the rod of men, with the stripes of the sons of men, but my steadfast love will not depart from him, as I took it from Saul, whom I put away from before you. And your house and your kingdom shall be made sure forever before me. Your throne shall be established forever.’ ”

- In **2 Sam 7** it's made clear David is not the serpent crusher. There is still one greater to come who will be a decendent of David.
- David's son Solomon takes the throne who partially fulfills this promise
- Solomon builds the temple, a permanent dwelling place for the Lord. The Temple contains the ark which acts as a symbol of God's Rule
- The land sees prosperity and there is peace at all four sides.
- Everything looks good ... but it does not last.
- Solomon marries foreign wives and begins to worship other Gods
- The kingdom divides. The Partial Kingdom is in ruins.
- Turns out Solomon was not the son that was prophesied about...

## Bible Study

- We will split into groups now
- Make sure to fill out your table with this weeks points, this time under the title 'The Partial Kingdom'

---