---
title: "YF Notes: The Partial Kingdom (talk)"
date: "2018-11-04"
categories: [yf_notes]
typora-root-url: ../../public/
bibliography: Library.bib
csl: ios-press-books.csl
draft: true
---

## INTRODUCTION

I've printed off all the passages that I will be referring to so you don't have to look them up. Try your best to follow along. I'll refer to the passage references as I go. As a reminder in **Gen 12** God made a promise with Abraham. He promises that Abraham would have decendants, that he would reach the promised land, that there he would recieve blessing and kings would come from him which would be a blessing to the nations under them Tonight, we will be covering  around 1200 years spanning from Abraham to Solomon so a lot to squeeze in. We see partial fulfilment of these promises. The aim is to not get lost in the detail but rather to see the sweep of the bible story line. I will stop at some important details which I don't want you to miss.

## GOD'S PEOPLE

### Abraham and Isaac

It is important to note that there was nothing particularly special about Abraham that he or his descendants deserved these promises. In **Gen 15** it is revealed that Abraham "believed in the Lord, and he counted it to him as righteousness". "He was accepted by God, not on the basis of his own Goodness but by faith in the promises of God" [@roberts2012 p. 55]. We can also tell from this passage that Abraham seems to have a bit of a problem. He and his wife are very old and have no children to carry on Abraham's name. Abraham and Sarah decide to take matters into their own hands and Abraham takes Sarah's maid, Hagar, as a wife who bears Abraham a son.


In **Gen 17**, God makes it clear here that His people will not rise from Hagar's son, but from a son born to Sarah as per the original plan. By taking Hagar as a wife, Abraham demonstrated that he did not have trust God's plan. However, true to God's promise, Sarah conceives and bears Isaac on her old age. When Isaac had grown up, God commands Abraham to take Isaac up to the mountain and sacrifice him on an altar

This time, if we look in in **Gen 22**, we see that Abraham demonstates a change in attitude. He walks Isaac up the mountain with out protest. "He knew that the future of the promises depended on Isaac's survival" [@roberts2012 p. 62]. "[T]here is now ... [a] confidence in the Lord, who will provide" [@sailhamer2017 p. 651]. True to his promise, God provides a ram. Abraham had to learn, if the gospel had to be fulfilled, only God could bring it about. Abraham names the mountain "the Lord will provide" as a tribute

Paul reminds us in **Ephesians 2** that we are saved though faith in that it is trusting in God's work that brings about salvation. It is important to remember this.

### Jacob and Esau

**Gen 25** Isaac grows up and marries Rebekah who gives birth to 2 sons, Esau and Jacob. The scheming Jacob receives his father's blessing as though he was not the first born Jacob doesn't deserve that privilege. He tricks his brother out of his birth right. Jacob means 'holder of the heel'. Twice he held his brother back.

Paul in **Romans 9** comments on this account "though they were not yet born and had done nothing either good or bad ... not because of works but because of him who calls". "If we are Christians today, it's not because we are better than anyone else; it's simply because [God chose us]" [@roberts2012 p. 63]. It's important to remember this as you see the in present time and in history, humans will find any way to feel inferior to others. We need to learn not to be like that. God later names Jacob 'Israel' which means "God Strives" as a reminder it is by God's effort, not ours.

## GOD'S RULE AND BLESSING

### God's Law

You'll' notice that the law is not yet established. Yet, Abraham is considered righteous. This is an important order. Salvation comes before the Law. God, through Moses, set up the system of the Law. The Law signifies God's rule. Following this law will bring blessing.

What God's Law does
- reveals our Sin (**Romans 3**)
- reveals his standards (**Matthew 5**)
- reveals our saviour (**Galatians 3**)

"God's law is not intended to be the means by which anyone gets right with God ... He redeems them before they recieve the law ... The Law reveals God's standard" [@roberts2012 pp. 69-70]. This is fortunate as it's clear early on that Israel are unable to keep this law. 

### God's Presence

In Exodus 25 onwards, we learn about the tabernacle. This was a place where God could set up a sacrificial system to partially clean them enough to allow Israel to be in his presence, despite their sin.

The writer of the letter in **Hebrews 10** in teaches us that these sacrifices never truly took away sin. Leviticus details the ceremonial acts which needed to take place. This involved lots of animal sacrifice. Only one man could enter the most Holy place and only once a year. This was not a pleasant system. Not only that, the Animal sacrifices were never truly sufficient and it's why they had to do it day after day.

**Hebrews 10** reminds us as Christians to be thankful we no longer have to carry out these sacrifices to enjoy fellowship with God. Christ's blood acted as a once and for all sacrifice.

## GOD'S PLACE

Next we have God's place. As we learned from last time, the promised land was Cannan. **Josh 21** reveals that God fulfils his promise of land to Israel by giving them land (but not all of it). They have also have rest at all 4 sides. God's People are under God's Rule, enjoying His blessing ('rest'). "Not one word of all the good promises that the Lord had made to the house of Israel had failed; all came to pass"

## GOD'S KING

### The Serpent crusher

But what of the serpent crusher of **Gen 3**?... Looking back to **Gen 49**, Israel knows that it will be one of Judah's decedents who will be ruler over all nations forever. Israel are still waiting for this. At this point, God has proven trustworthy with his promises.

### God's Judges

Israel goes through a series of Judges. In this stage of Israel's history, they go through a seemingly never-ending cycle where:
- Israel Sins
- God Judges by Allowing them to be Defeated
- Israel cries for Mercy
- God provides a Judge
- Land is at peace
- Israel Sins
- ...	

At the end of the book of Judges in **ch. 21** there is a remark that there was no king in Israel and each done what was right in their own eyes

### God Rejected as King

However, **1 Sam 8** points out that they did in fact have a king, God, but Israel had rejected Him and and sought after a human king like the other nations. If only we had a King like those other nations! They wanted what the other nations had - a human king to tell them what to do

God anticipates this back in **Deut 17** and allows them to appoint a king of his choosing when they reach the promised land. In order for Israel to receive the promised blessings, this king would have a lot of responsibility on his shoulders. God rules in his kingdom by means of a king. The blessings are reliant on that king "keeping all the words of this law and these statutes, and doing them"

### God's King and  Blessing

In **1 Sam**, Samuel, the good judge, appoints Saul as King. Saul sins and Samuel anoints David as his Saul's successor. **2 Sam** David becomes King

In **2 Sam 7** it's made clear David is not the serpent crusher. There is still one greater to come who will be a descendent of David. David's son Solomon takes the throne who partially fulfils this promise. Solomon builds the temple, a permanent dwelling place for the Lord. The Temple contains the ark which acts as a symbol of God's Rule. The land sees prosperity and there is peace at all four sides. Everything looks good ... but it does not last. Solomon marries foreign wives and begins to worship other Gods The kingdom divides. The Partial Kingdom is in ruins. Turns out Solomon was not the son that was prophesied about...

## Bible Study

We will split into groups now. Make sure to fill out your table with this weeks points, this time under the title 'The Partial Kingdom'

---